### ISSUE TITLE
Some drives in sidebar have wrong icon

### ISSUE THREAD

**Issue by solomongrundy6** [nokyan/resources#111]
In the sidebar, two (out of four) of my drives show the icon for an unrelated flatpak application (the adobe flash player).

[screenshot](https://i.postimg.cc/CKC2CpMC/resources-icon-error.png)

They are the only two that are listed under 'Type' as 'Flash storage', so I assume that's why it's using the icon associated with the flash player.

**Comment by nokyan** [comment]
Hi,

thanks for reporting the issue. Are you using an icon theme by any chance?

**Comment by solomongrundy6** [comment]
I'm using Papirus-Light, which is one of the themes installed by default on my distro.

**Comment by solomongrundy6** [comment]
Browsing through /usr/share/icons, 'flash' seems to associate with the application, while 'media-flash' associates with the drive icon I assume resources is looking for.

**Comment by nokyan** [comment]
Yep, that's the culprit. Resources ships its own icons, including an icon named "flash-symbolic" for flash devices, which has probably been overwritten by your theme. I will rename Resources' icon for flash devices but issues like these are exactly the reason why [stopthemingmy.app](https://stopthemingmy.app/) exists, especially if your theme has been preinstalled by your distribution.
