### ISSUE TITLE
Dependency gtk4 found: NO found 4.6.9 but need: '>= 4.8.0'

### ISSUE THREAD

**Issue by gitzone83** [nokyan/resources#12]
Ubuntu 22.04.3 LTS, gtk4.8.0 plus is not available right now it seems.

**Comment by nokyan** [comment]
Ubuntu 22.04 seems to use Gtk 4.6.9 and libadwaita 1.1.7, both of which are too old for Resources unfortunately. You can try to install it as Flatpak from [Flathub](https://flathub.org/apps/net.nokyan.Resources) or build and install it as a Flatpak locally.

**Comment by gitzone83** [comment]
I did try flatpak as well, but got this pearl which seems to imply also lack of compatibility 

```
flatpak install --user org.gnome.Sdk//45 org.freedesktop.Sdk.Extension.rust-stable//23.08 org.gnome.Platform//4

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/user/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
error: No remote refs found similar to ‘org.gnome.Sdk//45’
```

**Comment by nokyan** [comment]
Can you try `flatpak install --user org.gnome.Sdk org.freedesktop.Sdk.Extension.rust-stable org.gnome.Platform` and select 45, 23.08 and 45 respectively when it asks for it?

**Comment by gitzone83** [comment]
Nope, this rime error is different 

```
Looking for matches…
error: No remote refs found similar to ‘org.gnome.Sdk’

```

**Comment by nokyan** [comment]
Can you try it without --user?

**Comment by gitzone83** [comment]
Same issue 
````
Looking for matches…
error: No remote refs found similar to ‘org.gnome.Sdk’

```

**Comment by nokyan** [comment]
Do you have the Flathub repo installed? Try `flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo` to set up Flathub.

**Comment by gitzone83** [comment]
I had repo setup. I rebooted the laptop and then ran through your command and yeah, that completely broke my laptop ... it seems to have lost all desktop installation, no netplan etc. I had to reinstall it from scratch. I will try again, but in a VM. Not doing that again in my daily rider.

**Comment by nokyan** [comment]
I'm so sorry that that happened, I really don't know how though since that command is straight from the [Flathub setup page for Ubuntu](https://flathub.org/setup/Ubuntu).
