### ISSUE TITLE
Support for memory speed with EXPO / XMP profiles

### ISSUE THREAD

**Issue by carif** [nokyan/resources#122]
**Problem / Feature request:**
Under memory, the Resources app shows a memory speed of 4800 MT/s. However, the actual memory speed is not listed. The DIMM supports 4800 MT/s and AMD Expo profiles for 5600 and 6000 MT/s. 
When configuring for example the 5600 MT/s via AMDs EXPO profile, my BIOS lists the speed as DDR5 4800 @ 5600 MT/s. dmidecode on my OS lists the speed as "Configured Memory Speed: 5600 MT/s" and "Speed: 4800 MT/s". Resources only shows the 4800 MT/s.

**System details:**
Resources App: 1.2.1 (flatpak)
OS: Fedora 39

**Comment by nokyan** [comment]
Hi,
thanks for reporting the issue. And also thanks for reporting what `dmidecode` says, that's very helpful. :)
I'll look into it and likely push a branch for testing that tomorrow or so, shouldn't be too hard to fix.

**Comment by nokyan** [comment]
I've pushed on a branch called `expo-xmp-fix`, do you mind testing if it now shows the speed as expected?

**Comment by carif** [comment]
> I've pushed on a branch called `expo-xmp-fix`, do you mind testing if it now shows the speed as expected?

It works and shows the result as expected. Thx.
Not sure if you might want to keep both values for the speed, like `dmidecode` does.

**Comment by nokyan** [comment]
> > I've pushed on a branch called `expo-xmp-fix`, do you mind testing if it now shows the speed as expected?
> 
> It works and shows the result as expected. Thx. Not sure if you might want to keep both values for the speed, like `dmidecode` does.

Great! I think I'll stick with one value for speed, the configured speed is probably what most people want to know anyways.
