### ISSUE TITLE
[Feature] AMD GPU usage displayed not very useful

### ISSUE THREAD

**Issue by J-StrY** [nokyan/resources#127]
First of thank you for this great piece of software!

AMD GPU usage is mostly just jumping between 0% and 100% - similar to what most of the monitor software is displaying.

More useful usage stats would be usage as displayed by radeontop, I'm guessing that radeontop is taking more samples and then averaging them out.

**Comment by nokyan** [comment]
Hi,
which GPU do you use? Can you maybe send a video of that happening?

**Comment by J-StrY** [comment]
I have a RX580.

Here is a recording showing the usage behavior.
[2023-12-18 11-55-42.zip](https://github.com/nokyan/resources/files/13702247/2023-12-18.11-55-42.zip)

**Comment by nokyan** [comment]
Ah, I see. That's intended, Resources only shows the activity during this refresh by reading a file called 'gpu_busy_percent' somewhere in sysfs, it doesn't sample over the x last refreshes.

**Comment by nokyan** [comment]
> > Do you mind telling me which GPU?
> 
> It's RX 470. Mesa 23.2.1.

Could you run nvtop and see if it detects everything successfully?

**Comment by nokyan** [comment]
> > > > Do you mind telling me which GPU?
> > > 
> > > 
> > > It's RX 470. Mesa 23.2.1.
> > 
> > 
> > Could you run nvtop and see if it detects everything successfully?
> 
> It is. In fact it shows correct frequencies, power usage & temp same as Resources. In Resources all values are correct, except for "GPU Usage", "Video Encode Usage" and "Video Decode Usage". ![Screenshot from 2024-01-25 12-20-44](https://private-user-images.githubusercontent.com/35904842/299624005-b0b8e880-d805-44d5-bf5d-febf8d0a10b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODczMzAsIm5iZiI6MTcwNjE4NzAzMCwicGF0aCI6Ii8zNTkwNDg0Mi8yOTk2MjQwMDUtYjBiOGU4ODAtZDgwNS00NGQ1LWJmNWQtZmViZjhkMGExMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMzg1MWY0OTIyNGQ4YTNiOWZjNWMzNDdhNDZmN2Q1ZWVlMTAxNzEwNTM4NzY2ZjhhOWM1MTY2Yjc2Yjk2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xxv5GTrD4JBbtyFQHDSW5vT6Wx7xx3F6atucHQ6FElM)

Sorry, my mistake, but could you run ``nvtop -E -1`` instead (preferably with a bigger terminal window then as well)? Encoder/decoder usage is unfortunately not visible in your screenshot. For GPU usage, I'm gonna test using the sum of the GPU usages of individual processes instead of polling gpu_busy_percent since they represent the average usage between the current refresh and the refresh before that, whereas gpu_busy_percent works differently. This might yield a more preferable result.

**Comment by rurigk** [comment]
Its working on me, but be aware that its possible that your browser is not using hardware video decoding or its not using it via video hardware decoding

![image](https://github.com/nokyan/resources/assets/6665402/52649470-35f2-4076-82b0-ee863d701a7c)

For me in firefox i need to enable vaapi in order to be registered in Resources
![image](https://github.com/nokyan/resources/assets/6665402/255c1e1d-2469-4477-ab2d-d3a1e080af10)

Encoding metrics is also working when i record in OBS

**Comment by nokyan** [comment]
> > > > > > Do you mind telling me which GPU?
> > > > > 
> > > > > 
> > > > > It's RX 470. Mesa 23.2.1.
> > > > 
> > > > 
> > > > Could you run nvtop and see if it detects everything successfully?
> > > 
> > > 
> > > It is. In fact it shows correct frequencies, power usage & temp same as Resources. In Resources all values are correct, except for "GPU Usage", "Video Encode Usage" and "Video Decode Usage". ![Screenshot from 2024-01-25 12-20-44](https://private-user-images.githubusercontent.com/35904842/299624005-b0b8e880-d805-44d5-bf5d-febf8d0a10b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODczMzAsIm5iZiI6MTcwNjE4NzAzMCwicGF0aCI6Ii8zNTkwNDg0Mi8yOTk2MjQwMDUtYjBiOGU4ODAtZDgwNS00NGQ1LWJmNWQtZmViZjhkMGExMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMzg1MWY0OTIyNGQ4YTNiOWZjNWMzNDdhNDZmN2Q1ZWVlMTAxNzEwNTM4NzY2ZjhhOWM1MTY2Yjc2Yjk2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xxv5GTrD4JBbtyFQHDSW5vT6Wx7xx3F6atucHQ6FElM)
> > 
> > 
> > Sorry, my mistake, but could you run `nvtop -E -1` instead (preferably with a bigger terminal window then as well)? Encoder/decoder usage is unfortunately not visible in your screenshot. For GPU usage, I'm gonna test using the sum of the GPU usages of individual processes instead of polling gpu_busy_percent since they represent the average usage between the current refresh and the refresh before that, whereas gpu_busy_percent works differently. This might yield a more preferable result.
> 
> Here it is with `nvtop -E -1`. ![Screenshot from 2024-01-25 16-07-13-obfuscated](https://private-user-images.githubusercontent.com/35904842/299695031-7a6cc75e-c480-4898-a244-b9b45645c1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzEwNDgsIm5iZiI6MTcwNzc3MDc0OCwicGF0aCI6Ii8zNTkwNDg0Mi8yOTk2OTUwMzEtN2E2Y2M3NWUtYzQ4MC00ODk4LWEyNDQtYjliNDU2NDVjMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIwNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZmFmZWVkYWU5NDI3OTIyOGI0YjViYmY1ZmZlNDEzZjhiYTEyZWIwMmRjMzZkNzY5OGI3YjU2ODljOWUxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ASf2-_TZekGMhVoUGqCWIsv9IY9lvEZNbsJ2jByx1o)

Sorry for not replying, I didn't notice it. Your GPU decoder is not being used in that screenshot, Vivaldi probably fell back to software decoding, like @rurigk said.

**Comment by nokyan** [comment]
> > > > > > > > Do you mind telling me which GPU?
> > > > > > > 
> > > > > > > 
> > > > > > > It's RX 470. Mesa 23.2.1.
> > > > > > 
> > > > > > 
> > > > > > Could you run nvtop and see if it detects everything successfully?
> > > > > 
> > > > > 
> > > > > It is. In fact it shows correct frequencies, power usage & temp same as Resources. In Resources all values are correct, except for "GPU Usage", "Video Encode Usage" and "Video Decode Usage". ![Screenshot from 2024-01-25 12-20-44](https://private-user-images.githubusercontent.com/35904842/299624005-b0b8e880-d805-44d5-bf5d-febf8d0a10b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODczMzAsIm5iZiI6MTcwNjE4NzAzMCwicGF0aCI6Ii8zNTkwNDg0Mi8yOTk2MjQwMDUtYjBiOGU4ODAtZDgwNS00NGQ1LWJmNWQtZmViZjhkMGExMGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyNTAzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMzg1MWY0OTIyNGQ4YTNiOWZjNWMzNDdhNDZmN2Q1ZWVlMTAxNzEwNTM4NzY2ZjhhOWM1MTY2Yjc2Yjk2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xxv5GTrD4JBbtyFQHDSW5vT6Wx7xx3F6atucHQ6FElM)
> > > > 
> > > > 
> > > > Sorry, my mistake, but could you run `nvtop -E -1` instead (preferably with a bigger terminal window then as well)? Encoder/decoder usage is unfortunately not visible in your screenshot. For GPU usage, I'm gonna test using the sum of the GPU usages of individual processes instead of polling gpu_busy_percent since they represent the average usage between the current refresh and the refresh before that, whereas gpu_busy_percent works differently. This might yield a more preferable result.
> > > 
> > > 
> > > Here it is with `nvtop -E -1`. ![Screenshot from 2024-01-25 16-07-13-obfuscated](https://private-user-images.githubusercontent.com/35904842/299695031-7a6cc75e-c480-4898-a244-b9b45645c1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzEwNDgsIm5iZiI6MTcwNzc3MDc0OCwicGF0aCI6Ii8zNTkwNDg0Mi8yOTk2OTUwMzEtN2E2Y2M3NWUtYzQ4MC00ODk4LWEyNDQtYjliNDU2NDVjMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIwNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZmFmZWVkYWU5NDI3OTIyOGI0YjViYmY1ZmZlNDEzZjhiYTEyZWIwMmRjMzZkNzY5OGI3YjU2ODljOWUxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ASf2-_TZekGMhVoUGqCWIsv9IY9lvEZNbsJ2jByx1o)
> > 
> > 
> > Sorry for not replying, I didn't notice it. Your GPU decoder is not being used in that screenshot, Vivaldi probably fell back to software decoding, like @rurigk said.
> 
> That's alright. Well, I'm pretty sure something's off.
> 
> When using Firefox I noticed, that I have the failure code `FEATURE_HARDWARE_VIDEO_DECODING_DISABLE`, despite it was still good in any video-related task (8K for example) same as Vivaldi.
> 
> ![image](https://private-user-images.githubusercontent.com/35904842/306680717-e1a51340-629a-4cf1-bf0b-b18179bfb029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MzkyNjksIm5iZiI6MTcwODYzODk2OSwicGF0aCI6Ii8zNTkwNDg0Mi8zMDY2ODA3MTctZTFhNTEzNDAtNjI5YS00Y2YxLWJmMGItYjE4MTc5YmZiMDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIxNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YmJmNzU3NThmYWIyODRiMjAzYzJkYjM3MTUwOWZhZWM1ZjVjOWJjNjY1ODg0NTE2ODY5MGZhMzkzOGFkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7N97QpOQYz0knD47DYibp5ETXaqXTQo96bWTyeVAtFY)
> 
> This might be a clue. [Firefox hw-accel "blocklisted by env: Blocklisted by gfxInfo"](https://bbs.archlinux.org/viewtopic.php?id=281398) Still, have no idea whatsoever.

I also don't have any clue to be honest. As far as I know, getting info from the RX 470 should be the same as getting info from any other somewhat recent AMD GPU. Could you run Resources from the terminal using `flatpak run net.nokyan.Resources` (if you've installed it via Flatpak) and send me the terminal output?

To get back to the original issue, in the `save-last-opened-page` I've also implemented a potentially better way of displaying AMD GPU usage, could you test that @J-StrY ?

**Comment by rurigk** [comment]
I was playing AV1 from YouTube
