### ISSUE TITLE
Display the resource name in the sidebar when multiple resources of the type exists

### ISSUE THREAD

**Issue by justinas** [nokyan/resources#136]
For certain resources types, most notably network interfaces and storage drives, but in some cases also GPUs, multiple of them can exist in a single system.

In such cases, it would be great to display a short resource name (e.g. `nvme0`, `eth1`) in its sidebar item.

**Comment by nokyan** [comment]
Hi, thanks for the suggestion!
I agree, something to distinguish between would be good, though I'd like Resources to be accessible to non-tech-savvy users as well and I don't know if the resource names like eth1 are good for that. On the other hand, I don't know what else could be used for differentiation, except for maybe the device name (like "Realtek Ethernet RTL yada yada yada"). 🤷

**Comment by nokyan** [comment]
What do you think about this?

![image](https://github.com/nokyan/resources/assets/20604611/d55e7c1a-dead-4c1e-8cc8-2f9333508276)

It'll be disabled by default, though it can be enabled in the settings.

**Comment by nokyan** [comment]
> The graphs make each sidebar entry 3x larger than they currently are, which in the case of 5-10 network interfaces, makes the sidebar enormously tall.

You will be able to choose between full-blown graphs or the old progress bars in the sidebar, exactly for cases like yours with many drives or network interfaces. :)

> I'd just change the current sidebar to be a 2-line text field with the secondary text 70% of the first - as you also have in the mockup. That way the sidebar items only increases in height by 50% and not by 300-400%.

Yes, the new line of text is what I was mainly referring to.

**Comment by nokyan** [comment]
Fixed as of Resources 1.4. Don't hesitate to reopen if there's still something wrong. :)
