### ISSUE TITLE
Feature request : automatically hide the metrics that can't be measured 

### ISSUE THREAD

**Issue by houssemko** [nokyan/resources#137]
Exp : these metrics in the gpu section :
-video memory usage
-video memory frequency
-power usage 
![image](https://github.com/nokyan/resources/assets/41808005/ce6f398b-7d53-4eb6-93f7-4276d0b8deff)

**Comment by nokyan** [comment]
Hi, thanks for the suggestion.
I prefer Resources showing N/A because that way it's clear that this information can't be currently displayed by Resources. If Resources were to hide the N/A fields, it wouldn't be entirely clear whether Resources just doesn't show that information for any GPU in general, or whether it's just not available for that type of GPU.

**Comment by houssemko** [comment]
that's true.

**Comment by TheRsKing** [comment]
> Hi, thanks for the suggestion. I prefer Resources showing N/A because that way it's clear that this information can't be currently displayed by Resources. If Resources were to hide the N/A fields, it wouldn't be entirely clear whether Resources just doesn't show that information for any GPU in general, or whether it's just not available for that type of GPU.

I understand your point, it can be useful. However, I think it would be best if it could be turned on/off in the preferences.
Oh, and I would also like to say that I am fascinated by Resources.

**Comment by nokyan** [comment]
> > Hi, thanks for the suggestion. I prefer Resources showing N/A because that way it's clear that this information can't be currently displayed by Resources. If Resources were to hide the N/A fields, it wouldn't be entirely clear whether Resources just doesn't show that information for any GPU in general, or whether it's just not available for that type of GPU.
> 
> I understand your point, it can be useful. However, I think it would be best if it could be turned on/off in the preferences.

Making this customizable would just clutter up the preferences in my opinion.

> Oh, and I would also like to say that I am fascinated by Resources.

Thank you. :)
