### ISSUE TITLE
Feature Request: Add grid to graphs

### ISSUE THREAD

**Issue by pktiuk** [nokyan/resources#15]
I think graphs drawn by Resources need some grid in the background to make results a bit more readable.

Just like in resource monitor from gnome (or in windows)
![image](https://github.com/nokyan/resources/assets/45544416/24d32c68-12d3-4d57-a81c-2d7135f21369)

**Comment by nokyan** [comment]
Thank you for the issue. I see how it could help, but I also kind of like the simplicity of the current graphs. I also don't know whether the small logical CPU graphs have enough space to fit a grid without looking too crammed. I think I could make it toggleable.

**Comment by pktiuk** [comment]
I think that small CPU graphs don't need any grids.   
But in memory graphs it could be useful.   

Maybe other way of improving readability would be making memory graphs a bit bigger 🤔 

In general I think deciding about this issue can just wait. We can ask people about reacting under feature request issues using thumbs up and down.
