### ISSUE TITLE
CPU/GPU title mismatch

### ISSUE THREAD

**Issue by xnhunter** [nokyan/resources#152]
Resources v1.3.0

Ubuntu 23.10 / kernel version 6.5.0-14

![image-cpu](https://github.com/nokyan/resources/assets/35904842/0888677a-e560-4d2e-8de1-90bf4442c260)

![image](https://github.com/nokyan/resources/assets/35904842/813f2280-9620-4df2-9b3a-0f276188a7f1)

**Comment by nokyan** [comment]
Hi, thanks for raising the issue. :)
This must've flown under my radar for the past few months somehow, but I noticed this a few days ago as well and it's fixed as of commit 1beb3ab and will be released with Resources 1.4 soon. :)
I'm closing this, don't hesitate to reopen if needed. ^^
