### ISSUE TITLE
[Feature] Assign "DEL" keyboard shortcut to sigkill

### ISSUE THREAD

**Issue by BrandowLucas** [nokyan/resources#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Kinda of, having a shortcut to kill processes is way more practical and faster than the using the mouse to end a process.

### Describe the solution you'd like

Assign "DEL" (delete) shortcut to a kill signal for a selected process/application.

### Additional context

Other than that, this task manager is the holy grail and perfection, congrats!

**Comment by nokyan** [comment]
Hi, thanks for your suggestion!
This fits really well with my plans about QoL and accessibility improvements for Resources 1.4, I'll put it on the list. Though the past few days (and probably also the next few days or weeks) I've been quite busy with my studies, so I unfortunately don't have too much time to work on Resources.
Oh, and I'm glad that you like Resources. :)

**Comment by techeddie** [comment]
@nokyan, hi, 
thanks for this nice application. I have version 1.3.0 installed via flatpak. 
You mentioned more shortcuts have been added but I'm not able to kill via DEL or Shift+DEL.
Is there an option to map own shortcuts or remap existing?

**Comment by nokyan** [comment]
> @nokyan, hi, thanks for this nice application. I have version 1.3.0 installed via flatpak. You mentioned more shortcuts have been added but I'm not able to kill via DEL or Shift+DEL. Is there an option to map own shortcuts or remap existing?

Hi, thank you, I'm glad you like Resources. :)
The shortcuts haven't landed yet, I hope to release Resources 1.4 shortly after GNOME 46 releases so the new libadwaita 1.5 stuff can be implemented as well. I don't think the shortcuts will be remappable, but you'll be able to use CTRL + E for ending and CTRL + K for killing applications as well.
