### ISSUE TITLE
Json endpoint for remote visualization

### ISSUE THREAD

**Issue by ecerichter** [nokyan/resources#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I want to use a tablet or old cell phone as screen visualization for my computer metrics. Todo so, I would like to create a angular app that will query metrics through the network. That's why I would like to have a endpoint.

### Describe the solution you'd like

Provide an endpoint where I can query the metrics and get response as json.

### Describe alternatives you've considered

Using the tablet or cell phone as additional screen, but it is unpractical for long term.

**Comment by nokyan** [comment]
Hi, thanks for the suggestion.
I feel like this is quite out of scope for Resources, sorry.
