### ISSUE TITLE
Add temperature indicator when "Show usage details" is enabled

### ISSUE THREAD

**Issue by CiscoDeTours** [nokyan/resources#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

A temperature indicator must replace the not so useful GPU VRAM percentage and should be added to the processor details.

### Describe the solution you'd like

![TIFR](https://github.com/nokyan/resources/assets/67841579/7f25417a-ffe4-4ba0-bfd3-b9b96c37bf9c)

### Describe alternatives you've considered

None.

### Additional context

As the image shows, it's highly recommended to use a bold font to highlight the temperature.

**Comment by nokyan** [comment]
Hi, thanks for the suggestion.
I don't think I agree that temperature is more important than VRAM. There's space for VRAM and temperature though, maybe I'll do that. :)

**Comment by nokyan** [comment]
![image](https://github.com/nokyan/resources/assets/20604611/19a681ec-32c9-4fab-96a8-c2a3053199e2)
I've implemented it, what do you think?

**Comment by CiscoDeTours** [comment]
Well done. Thanks a lot for the addition.
