### ISSUE TITLE
[Feature] Remember selected sort column

### ISSUE THREAD

**Issue by popov895** [nokyan/resources#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, if I change the sort column on the "Applications" and "Processes" pages, then this change remains only until the application is restarted. It would be great if this change was persistent across the application restart.

**Comment by nokyan** [comment]
Hi, thanks for the suggestion. Sounds good, I'll put it on the list.

**Comment by popov895** [comment]
Thanks!
