### ISSUE TITLE
[Feature] Remember selected page

### ISSUE THREAD

**Issue by popov895** [nokyan/resources#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, when launching the application, the active page is always the "Applications" page. It would be great if the last open page became active when the application is launched.

**Comment by nokyan** [comment]
Hi, thanks for the suggestion. I'll put it on the list.

**Comment by popov895** [comment]
I think this feature may/should be optional.

**Comment by popov895** [comment]
Thanks!
