### ISSUE TITLE
Afrikaans translation.

### ISSUE THREAD

**Issue by odofad** [nokyan/resources#165]
I like and use resources, and so translated into Afrikaans. This is my first translation contribution so not sure how to commit it. 
[af_ZA.zip](https://github.com/nokyan/resources/files/14241413/af_ZA.zip)

**Comment by nokyan** [comment]
Hi, thank you very much for your submission.
I'm gonna commit this one myself later, I think [these](https://docs.github.com/en/get-started/using-git/about-git) [links](https://docs.github.com/en/get-started/using-git/about-git) will help you with how git and GitHub works. :)

**Comment by odofad** [comment]
Cool thanks, I'll definitely give that a read.
