### ISSUE TITLE
Missing `undershoot-bottom` shadow on applications' and processes' colimnviews

### ISSUE THREAD

**Issue by garaevdi** [nokyan/resources#169]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

There are no `undershoot-bottom` shadow

### Expected Behavior

There should be one

### Environment

```markdown
Program version: 1.3.0
Package type: flatpak
```

### Anything else?

According to [adwaita style classes for undershoots](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/style-classes.html#undershoot-indicators) it's recommended to use `AdwToolbarView`, which can mange them automatically. But currently applications and processes pages make bottom toolbar using vertical `GtkBox`.

Comparison:
| With `GtkBox` | With `AdwToolbarView` |
|--------|--------|
| ![image](https://github.com/nokyan/resources/assets/64484944/a68c5bc1-b6fd-4e10-9e67-969888a4c030) | ![image](https://github.com/nokyan/resources/assets/64484944/f9eba26d-6dcf-498b-acda-096e33540970) |

**Comment by nokyan** [comment]
Hi, thank you very much for your issue.
I'll look into it, it seems like it should be relatively easy to fix. :)
