### ISSUE TITLE
Headerbar style is inconsistent

### ISSUE THREAD

**Issue by ADBeveridge** [nokyan/resources#17]
The Applications and Processes stack pages have a raised Headerbar, but every other page has a flat headerbar. I would stick with raised throughout, since the Memory page can have a Adw.Banner for authentication.

**Comment by nokyan** [comment]
Thank you for the issue. Applications and Processes don't have an explicitly raised headerbar, it's just that the Column Views inside them have a different background color, I'll see what I can do, a have few bugfixes that take priority though.
