### ISSUE TITLE
Memory reported is off by 1024/1000

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#176]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Total memory reported by `free -m` and the GUI would agree.

"Free" Total Mem: 64152 (MiB) -> 62.65 GiB
"Free" Total Swap: 16383 (MiB) -> 16.00 GiB

App Total Mem: 61.18 GiB
App Total Swap: 15.62 GiB

Let it be known that:
61.18 * 1024 / 1000 = 62.65
15.62 * 1024 / 1000 = 16.00

### Expected Behavior

Memory reported in `free` and the app would be approximately equal

### Steps To Reproduce

 - Set data unit to `Binary`
 - Go to memory page
 - Observe max memory and swap
 - run `free --m`
 - divide reported total memory and swaps by `1024`

### Environment

```markdown
1.3.0, installed via flatpak.
```

### Anything else?

The issue is because here V 
https://github.com/nokyan/resources/blob/24f71a0ab78df0409569ab014c5bdb38e5900bfd/src/utils/memory.rs#L64-L78
you assume that meminfo reports in KiloBytes, but unfortunately is is actualy KibiBytes, so you would need to take out the 1024 before multiplying in the 1000's. (I checked this by running `free -k` and getting the same value in `meminfo`)

**Comment by nokyan** [comment]
Hi, thanks for reporting the issue.
/proc/meminfo says "kB", so I assumed proper kilobytes, but kibibytes does indeed make more sense here. I should've noticed that earlier tbh. ^^
Fix is on the way.
