### ISSUE TITLE
Ability to select multiple processes or apps at once

### ISSUE THREAD

**Issue by RushingAlien** [nokyan/resources#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Sometimes I would like to batch stop multiple processes.

### Describe the solution you'd like

The ability to select multiple processes not just via picking one by one, but by holding shift to select rows of processes and ctrl for individual rows, or a toggleable select mode (maybe via holding one of the row or a button)

### Describe alternatives you've considered

selecting and stoppping one by one

### Additional context

![gambar](https://github.com/nokyan/resources/assets/80886145/c4de85bc-8cbc-4821-be02-318411401dd8)

system monitor for an example

**Comment by nokyan** [comment]
Hi, I've implemented multiple selection for processes in the [`multiple-processes-selection`](https://github.com/nokyan/resources/tree/multiple-processes-selection) branch, do you mind checking it out?
