### ISSUE TITLE
Ability to add more info collumns in processes and app view

### ISSUE THREAD

**Issue by RushingAlien** [nokyan/resources#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'd like to be able to view more metrics at a glance if I can

### Describe the solution you'd like

A context menu or a window dialog that let me add or subtract certain collumns

### Describe alternatives you've considered

entering information of individual processes

**Comment by nokyan** [comment]
Hi,
you can already toggle columns in the settings. Open the hamburger menu (button with three horizontal lines) on the top right of the sidebar and click "Settings". In the "Applications" and "Processes" tabs you can toggle each column individually.

**Comment by RushingAlien** [comment]
Ah thanks, My apologies
