### ISSUE TITLE
User information of process is not correct

### ISSUE THREAD

**Issue by starlitfuture** [nokyan/resources#182]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Any process started by other users rather than current user will be recognized as "root".
![Screenshot from 2024-03-10 23-35-25](https://github.com/nokyan/resources/assets/70831342/655b75c2-ba61-4918-bc14-bcb45b35741b)

### Expected Behavior

Show correct user information.
![Screenshot from 2024-03-10 23-37-46](https://github.com/nokyan/resources/assets/70831342/cb4bac31-1f1b-4188-828f-7bae27870dd6)

### Steps To Reproduce

1. Go to "Process Page".
2. Select a process.

### Environment

```markdown
Program Version: 1.3.0
Package type: Flatpak
System: Gentoo Linux
Desktop Environment: Gnome 45.2
Kernel Version: 6.7.9-gentoo-dist
Hardware Info: Intel i7-8750H, 32GB RAM, Intel UHD 630, Nvidia GTX 1060
```

**Comment by nokyan** [comment]
Hi, thanks for reporting the issue.
I'm using the `uzers` crate for Rust to get user names for a given user ID. Resources calls users, whose user name can't be found, "root" as a fallback. I don't exactly know why that seems to fail, but I'll look into it. Maybe I'm just using it wrong. 🤷

**Comment by nokyan** [comment]
Hi, I pushed a fix in the `user-names-fix` branch, do you mind checking it out?

**Comment by starlitfuture** [comment]
> Hi, I pushed a fix in the `user-names-fix` branch, do you mind checking it out?

Hi, sorry for late respond. I have tested it on my Fedora VM and it is working fine now. Thank you for your work!
![Screenshot from 2024-04-14 23-02-28](https://github.com/nokyan/resources/assets/70831342/e5b1d17c-331e-4efa-8b6a-552dc9f92f2f)
