### ISSUE TITLE
GUI Toggle for dark mode

### ISSUE THREAD

**Issue by BeaverMech** [nokyan/resources#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm a Linux noob, so this may be obvious. I've set both global theme and GTK settings to dark modes, but Resources is still stuck in light mode. Arch+KDE Plasma. 

### Describe the solution you'd like

A toggle in options to force dark mode for plebs like me would be a lifesaver

**Comment by nokyan** [comment]
Hi, thanks for the issue.

I don't use Plasma, so I unfortunately can't help you on that side, but I'm pretty sure that changing a dark theme toggle somewhere in Plasma's settings should also apply to libadwaita-based apps.
I'd prefer not implementing a theme toggle as that should be handled by the desktop environment.
Did you install Resources via Flatpak?

**Comment by BeaverMech** [comment]
Hi, thanks for your response. I did install via flatpak. Potentially relevant is this is on steamOS, which seems to be a bastardized version of Arch

**Comment by nokyan** [comment]
I'm closing this issue since you found a solution. :)
