### ISSUE TITLE
CPU time column

### ISSUE THREAD

**Issue by Mr-Blue-Sky-Candy** [nokyan/resources#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

**Total CPU time including system and user in the processes tab** would allow investigating processes consuming actual CPU capacity over the complete period a process running instead of at the time we are looking at the Resources. This allows which programmes actually consume the most amount of power. In addition, this would allow eliminating processes that occupy CPU but not necessary during intense calculations such as AI training.

**Comment by nokyan** [comment]
Hi, thanks for the issue.
This should be relatively straight forward to implement since Resources already keeps track of CPU time in order to calculate the CPU usage percentage. It doesn't differentiate between system and user CPU time yet, though this should also be relatively simple.

**Comment by nokyan** [comment]
If you want to, you can check it out in the `cpu-time` branch.

**Comment by Mr-Blue-Sky-Candy** [comment]
Great! Separating user and system is not necessary unless the person looking at this is a system administrator. To track the cpu power consumption, total including both would be useful. I cannot check it right now but thank you very much.
