### ISSUE TITLE
Resources Symbolic Icon

### ISSUE THREAD

**Issue by nobodywatchin** [nokyan/resources#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I use a gnome extension called 'vitals' which by default has a button that opens gnome-system-monitor

I prefer resources, however, 

When I changed the button to open resources, it works, but appears this way:
![Screenshot from 2024-04-16 10-53-55](https://github.com/nokyan/resources/assets/118339799/6ac8195d-5700-49cf-87b1-73bb1d34d5b2)

The gnome-system-monitor has its own symbolic icon that the extension calls, so I'm requesting that we add one to resources.

### Describe the solution you'd like

Add this icon to the program so that a symbolic icon can be called

I whipped this up using the original resources SVG file as a base

![net nokyan Resources-symbolic](https://github.com/nokyan/resources/assets/118339799/9aabcd5d-4076-4357-a90e-adc5c8ecd48f)

**Comment by nokyan** [comment]
Hi,
Resources does have a symbolic icon here: https://github.com/nokyan/resources/blob/main/data/icons/net.nokyan.Resources-symbolic.svg. I'm confused as to why it wouldn't show up there, since it also gets installed and exported by Flatpak properly as far as I know.

**Comment by nobodywatchin** [comment]
this is actually likely a problem with vitals as opposed to resources then, i think I can find a workaround
