### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by mfascioglu** [nokyan/resources#206]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

it looks like this after last update.

https://github.com/nokyan/resources/assets/104912991/9a4d84a7-00f6-4b5c-bc43-f942fcc77c4d

### Expected Behavior

Everything should look normal.

### Steps To Reproduce

1. Update Resources to lastest version.
2. Start Resources.

### Environment

```markdown
Program Version: 1.4.0
Package type: Flatpak
System: Debian 12 (Bookworm)
uname -a output:
6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

Hardware info: Intel Core i7-4700mq, 16GB RAM, Nvidia Geforce GT755M 2GB
Nvidia Driver Version: 470.223.02
Window System Protocol: X11
```

**Comment by nokyan** [comment]
Hi, thanks for the issue.
That's definitely not expected behavior. Can you run `flatpak run net.nokyan.Resources` from your terminal and send me the output? Does this happen with other apps using the GNOME 46 runtime like [Tuba](https://flathub.org/apps/dev.geopjr.Tuba) as well?

**Comment by mfascioglu** [comment]
Hi,
I did not have Mastodon account. I tried create account for return to you. I created it but it is not approved yet. Everything looks fine for Tuba now.👇
When account is approved i will sign in and return here.
Thank you.
![image](https://github.com/nokyan/resources/assets/104912991/2e2da63c-9fa9-4bbc-890e-4ee5e8ea5a96)
```
$ flatpak run net.nokyan.Resources
 INFO  resources::application > Resources (net.nokyan.Resources)
 INFO  resources::application > Version: 1.4.0 ()
 INFO  resources::application > Datadir: /app/share/resources
 DEBUG resources::utils       > Running as Flatpak
 DEBUG resources::utils::memory > Memory information obtained using udevadm
 DEBUG resources::utils::app    > Detecting installed applications…
 DEBUG resources::utils::app    > The following locales will be used for app names and descriptions: ["tr_TR.UTF-8", "tr_TR", "tr"]
 DEBUG resources::utils::app    > Detected 207 applications
 DEBUG resources::utils::pci    > Parsing pci.ids…
 DEBUG resources::utils::pci    > Successfully parsed pci.ids
 DEBUG resources::utils::gpu::nvidia > Successfully connected to NVML
 DEBUG resources::utils::gpu         > Found GPU "NVIDIA GeForce GT 755M" (PCI slot: 0000:01:00.0 · PCI ID: 10de:fcd · Category: NVIDIA)
 DEBUG resources::utils::gpu         > Found GPU "NVIDIA GeForce GT 755M" (PCI slot: 0000:07:00.0 · PCI ID: 10de:fcd · Category: NVIDIA)
 DEBUG resources::utils::cpu         > CPU temperature sensor located at /sys/class/hwmon/hwmon3/temp1_input (coretemp)
 DEBUG resources::ui::window         > A drive has been added (or turned visible): /sys/block/sdb
 DEBUG resources::ui::window         > A drive has been added (or turned visible): /sys/block/sdc
 DEBUG resources::ui::window         > A drive has been added (or turned visible): /sys/block/sda
 DEBUG resources::ui::window         > A network interface has been added (or turned visible): /sys/class/net/wlp9s0
 DEBUG resources::ui::window         > A network interface has been added (or turned visible): /sys/class/net/enp8s0
```

**Comment by nokyan** [comment]
You didn't need to make a Mastodon account for that, perhaps I should have picked a more appropriate app to test. 😅
You said in the original post that you updated to 1.4, I assume this bug did not occur on Resources 1.3?

**Comment by mfascioglu** [comment]
I did not know do not need to make a Mastodon account. Beacause this is my first Tuba experience. It was asking for the server address to proceed to the next step.😅 If you know a more appropriate app with GNOME 46 runtime, i can test it.

Exactly. There was no problem in version 1.3.

GPUs are does not twice detected. I have 2 GPU but i can not use with SLI. Nvidia does not support SLI on Linux. The second gpu does not rendering.

Lenovo Ideapad Y510p: https://www.notebookcheck.net/Review-Lenovo-IdeaPad-Y510p-Notebook.97470.0.html

**Comment by mfascioglu** [comment]
I did not know do not need to make a Mastodon account. Beacause this is my first Tuba experience. It was asking for the server address to proceed to the next step.😅 If you know a more appropriate app with GNOME 46 runtime, i can test it.

Exactly. There was no problem in version 1.3.

GPUs are not detected twice. I have 2 GPU but i can not use with SLI. Nvidia does not support SLI on Linux. The second gpu is not rendering.

Lenovo Ideapad Y510p: https://www.notebookcheck.net/Review-Lenovo-IdeaPad-Y510p-Notebook.97470.0.html

**Comment by nokyan** [comment]
You could try [Secrets](https://flathub.org/apps/org.gnome.World.Secrets), it's also using GNOME 46.
I didn't know SLI in notebooks was a thing, that's interesting.
I frankly don't have any clue what could be causing this issue because I haven't touched any code related to rendering since 1.3. The only custom rendering that Resources does are the graphs and they seem to be working perfectly fine in contrast to anything else for some reason. :/

**Comment by mfascioglu** [comment]
This is so interesting. I am using [DebianStable](https://wiki.debian.org/DebianStable). Secret has the same problem. Maybe the problem is caused by Debian's Nvidia driver or maybe kernel. I will follow driver and kernel updates. if the problem is fixed I will report back. Thank you for your interesting.


https://github.com/nokyan/resources/assets/104912991/ef31391b-890d-4cd3-85ab-fd4fc58a4d0a

**Comment by garaevdi** [comment]
I don't really like to revive old issues, but if anyone would like to hear the solution....

 Possibly this is because of new GTK renderers (https://gitlab.gnome.org/GNOME/gtk/-/issues/6574). Setting environment variable `GSK_RENDERER=gl` will tell GTK to use old renderer (note: for flatpak you can type `flatpak override --user --env=GSK_RENDERER=gl` to set this variable for all flatpak applications). Though I can't really confirm this, because I don't own an nvidia gpu.

As for Tuba, they are [forcing old renderer](https://github.com/GeopJr/Tuba/blob/069170311ac3f26d624b688c819f8bd6d6990d79/src/Application.vala#L209).

**Comment by mfascioglu** [comment]
Hi,
 `flatpak override --user --env=GSK_RENDERER=gl` is works with nvidia-tesla-470-driver.

Note: I tried with Nouveau driver (without  `flatpak override --user --env=GSK_RENDERER=gl`) app is running normal.

Thank you @garaevdi
