### ISSUE TITLE
Wrong detection of the number of logical cpus 

### ISSUE THREAD

**Issue by adm313** [nokyan/resources#209]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Hi 
I've lately installed Resources and I've seen that it is doubling the number of logical cpus.
My system is a Lenovo P900 with 2 E5-2690V3 cpus (12 core each).
The overall number should be 48 as lscpu & htop show but Resources show 96  ....

### Expected Behavior

Show 48 graphs  instead of 96

### Environment

```markdown
Version 1.4.0
Flatpak distribution
Ubuntu 23.10
```

### Anything else?

![image](https://github.com/nokyan/resources/assets/105816964/fc76d037-944e-415f-9db1-bd0e959595bb)

**Comment by adm313** [comment]
I've taken a look at the source and (maybe) the error is here
capture
                .as_str()
                .parse::<usize>()
                .ok()
                .map(|int| int * **sockets.unwrap_or(1)**)
        })

The cpu number is already doubled in the CPUs field of lscpu output.

**Comment by nokyan** [comment]
Sweet, I'm gonna fix that soon. I'll add this multiplication with sockets for physical CPUs though, I think that's more intuitive instead of showing the physical CPUs of just one CPU.
If I can find some more smaller bugs to squash, I'll release this fix with Resources 1.4.1. :)
