### ISSUE TITLE
AMD video encoder usage is actually decoder usage and vice versa

### ISSUE THREAD

**Issue by freaktechnik** [nokyan/resources#212]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The "Video Encoder Usage" tracks the usage of hardware decoding, the "Video Decoder Usage" presumably tracks the usage of hardware encoding.

### Expected Behavior

The "Video Encoder Usage" tracks the usage of hardware encoding, "Video Decoder Usage" tracks the usage of hardware decoding.

### Steps To Reproduce

1. Have an AMD GPU where this reproduces (in my case an 7900 XTX)
2. Select the GPU
3. Use hardware decoding to play a video
4. Video Decoder Usage stays at 0%, while Video Encoder Usage shows activity

### Environment

```markdown
Program Version: 1.4.0
Package Type: Flatpak
System: Fedora 39 (Linux 6.8.4-200.fc39.x86_64, Gnome 45.5)
Graphics (shown as GPU 2 in Resources): AMD Radeon™ RX 7900 XTX
```

**Comment by nokyan** [comment]
Hi, this is known and an unfortunate side effect of AMD merging the decoder and encoder parts of their media engine since RX 7xxx. I haven't yet found a way to properly find out whether a GPU has this new merged engine or the old seperated engine, and I'd really like to avoid using regex on the GPU name or hardcoding a list of PCI IDs. :/

**Comment by Umio-Yasuno** [comment]
I think the VCN HW IP version we can get from `ip_discovery` sysfs (`ip_discovery/die/0/UVD/0/major`) will be helpful.  
Currently, VCN v4.x (major version: 4) or higher have unified decoding and encoding queues.

**Comment by patrulhasirius** [comment]
I think I'm having the same issue in an intel iGPU, is it the same reason or should I report it?

Firefox is showing encoder usage and no decoder usage while playing a youtube video.

**Comment by nokyan** [comment]
> I think I'm having the same issue in an intel iGPU, is it the same reason or should I report it?
> 
> Firefox is showing encoder usage and no decoder usage while playing a youtube video.

Hi, the reason for that is the same as for newer AMD GPUs, Intel GPUs unfortunately do not differentiate between encode and decode and I haven't yet found a way to make this work in the Apps and Processes pages.

**Comment by nokyan** [comment]
Hi, I've pushed a branch [`combined-media-engines`](https://github.com/nokyan/resources/tree/combined-media-engines) that should now recognize AMD GPUs with combined media engines and handles them in the Apps/Processes lists a bit better. If the media engine of a GPU with combined encoder/decoder stats is used, the percentage will now be displayed in both the encoder and decoder columns in Apps/Processes. Still not ideal of course but less confusing than it is now I think.
I'd appreciate if you could test it.

**Comment by Umio-Yasuno** [comment]
Since `ip_discovery` shares the same ID with UVD and VCN, I noticed that the the `GC` major version check is also necessary for accurate combined media engine detection.  
I wrote a patch, but since I'm using Debian stable I couldn't check the compilation.　　

```diff
---
 src/utils/gpu/amd.rs | 9 +++++----
 1 file changed, 5 insertions(+), 4 deletions(-)

diff --git a/src/utils/gpu/amd.rs b/src/utils/gpu/amd.rs
index a2676a5..1a97b1e 100644
--- a/src/utils/gpu/amd.rs
+++ b/src/utils/gpu/amd.rs
@@ -48,10 +48,11 @@ impl AmdGpu {
             combined_media_engine: false,
         };
 
-        if let Ok(vcn_version) = gpu.read_device_int("ip_discovery/die/0/UVD/0/major") {
-            if vcn_version >= 4 {
-                gpu.combined_media_engine = true;
-            }
+        if let [Ok(gc_version), Ok(vcn_version)] = [
+            gpu.read_device_int("ip_discovery/die/0/GC/0/major"),
+            gpu.read_device_int("ip_discovery/die/0/UVD/0/major"),
+        ] {
+            gpu.combined_media_engine = gc_version >= 9 && vcn_version >= 4;
         }
 
         gpu
-- 
```

**Comment by nokyan** [comment]
> Since `ip_discovery` shares the same ID with UVD and VCN, I noticed that the the `GC` major version check is also necessary for accurate combined media engine detection. I wrote a patch, but since I'm using Debian stable I couldn't check the compilation.　　
> 
> ```diff
> ---
>  src/utils/gpu/amd.rs | 9 +++++----
>  1 file changed, 5 insertions(+), 4 deletions(-)
> 
> diff --git a/src/utils/gpu/amd.rs b/src/utils/gpu/amd.rs
> index a2676a5..1a97b1e 100644
> --- a/src/utils/gpu/amd.rs
> +++ b/src/utils/gpu/amd.rs
> @@ -48,10 +48,11 @@ impl AmdGpu {
>              combined_media_engine: false,
>          };
>  
> -        if let Ok(vcn_version) = gpu.read_device_int("ip_discovery/die/0/UVD/0/major") {
> -            if vcn_version >= 4 {
> -                gpu.combined_media_engine = true;
> -            }
> +        if let [Ok(gc_version), Ok(vcn_version)] = [
> +            gpu.read_device_int("ip_discovery/die/0/GC/0/major"),
> +            gpu.read_device_int("ip_discovery/die/0/UVD/0/major"),
> +        ] {
> +            gpu.combined_media_engine = gc_version >= 9 && vcn_version >= 4;
>          }
>  
>          gpu
> -- 
> ```

Thank you, I included it in the `more-accurate-amd-media-engine-detection` branch. It works for my RX 6800 XT which doesn't have a unified media engine. Could someone with a RX 7xxx GPU test it?
