### ISSUE TITLE
Attempting to copy process information confusion

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#215]
### Steps to reproduce

- Start resources as non-privileged user
- Pull up info on a root process (ctrl + i)
- Take any field, and highlight some text (in my case PID)
- Try to copy it (ctrl + c)
- Resources needs superuser auth ???

### Expected Behavior

The highlighted field will be copied to the clipboard

### Environment

```markdown
1.4.0 via flatpak on Pop!_OS 22.04 LTS
```

### Suggestion

If nothing else, please put a little clipboard icon across from each field so that copying is possible? or perhaps disable that keybind when the info menu is pulled up?

**Comment by nokyan** [comment]
Hi, thanks for the issue.
This is because CTRL+C also tries to continue an application or process. I guess I can change that shortcut.
