### ISSUE TITLE
Inserting or removing a drive resets chart previews

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#216]
### Current Behavior

- Leave Resources alone to build up some entropy
- Observe beautiful memory chart (in sidebar)
- Insert flash drive into system
- Once detected and chart added for flash drive disk, the memory history will have reset!

### Expected Behavior

The new chart will be added (with no history) and all the other unaffected charts will be just that--unaffected

### Environment

```markdown
1.4.0 via flatpak on Pop!_OS 22.04
```

### Potentially Pertinent Settings

- Refresh Speed: Normal
- Show Graph Grids: true
- Graph Data Points: 300
- Show Usage Details in Sidebar: true
- Show Device Descriptions in Sidebar: true
- Sidebar Meter Type: Graph

- Show Virtual Drives: false
- Show Virtual Network Interfaces: true

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I can reproduce it and I'll look into it.

**Comment by nokyan** [comment]
I've pushed a change in `dont-reset-sidebar-charts`, do you mind testing it?
