### ISSUE TITLE
Add swap memory column

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#217]
### Problem
When I am deep into using swap, I cant figure out what process to kill since the memory reported does not account for memory swapped out. I therefore want to know exactly how much memory each process/app is demanding even when my 128 GiB swap partition is nearly full.

### Possible Solution

Add the option to have a `swap` memory column, and/or a `swap+memory` column so I can pick which metric to keep track of

**Comment by nokyan** [comment]
Hi, thanks for the issue.
This should be possible, I'll look into it.

**Comment by jojo2357** [comment]
I presume you are using `/proc/pid/stat` for that memory, and according to [this so](https://stackoverflow.com/a/60441542) there is an entry for total memory, swap and resident

**Comment by nokyan** [comment]
Hi, do you mind checking the [`swap-columns`](https://github.com/nokyan/resources/tree/swap-columns) branch out?

**Comment by jojo2357** [comment]
Ill get on it soon :saluting_face:

**Comment by jojo2357** [comment]
it wouldnt build in builder out of the box. `Requested extension org.freedesktop.Sdk.Extension.rust-stable/x86_64/47 not installed` and reinstalling SDK's did nothing

**Comment by nokyan** [comment]
> it wouldnt build in builder out of the box. `Requested extension org.freedesktop.Sdk.Extension.rust-stable/x86_64/47 not installed` and reinstalling SDK's did nothing

Oh yeah, I recognize that error, I believe it's a Flatpak bug. What Flatpak actually wants is org.gnome.Sdk//47 and org.gnome.Platform//47

**Comment by nokyan** [comment]
Have you had the chance to try it out again yet?

**Comment by jojo2357** [comment]
I just tried it, and it doesnt work. I get no apps nor processes with the following spam:

```
failed to fill whole buffer
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at resources/_build/cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1989:27
   2: resources::utils::process::Process::all_data
             at resources/src/utils/process.rs:99:13
   3: resources::ui::window::MainWindow::gather_refresh_data
             at resources/src/ui/window.rs:493:13
   4: resources::ui::window::MainWindow::periodic_refresh_all::{{closure}}::{{closure}}
             at resources/src/ui/window.rs:694:28
   5: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
   6: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:538:17
   7: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
   8: std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
   9: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  10: std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  11: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:537:30
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
  15: std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/pal/unix/thread.rs:108:17
  16: <unknown>
  17: clone
```

**Comment by nokyan** [comment]
> I just tried it, and it doesnt work. I get no apps nor processes with the following spam:
> 
> ```
> failed to fill whole buffer
>    0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
>              at resources/_build/cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14
>    1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1989:27
>    2: resources::utils::process::Process::all_data
>              at resources/src/utils/process.rs:99:13
>    3: resources::ui::window::MainWindow::gather_refresh_data
>              at resources/src/ui/window.rs:493:13
>    4: resources::ui::window::MainWindow::periodic_refresh_all::{{closure}}::{{closure}}
>              at resources/src/ui/window.rs:694:28
>    5: std::sys::backtrace::__rust_begin_short_backtrace
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
>    6: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:538:17
>    7: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
>    8: std::panicking::try::do_call
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
>    9: std::panicking::try
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
>   10: std::panic::catch_unwind
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
>   11: std::thread::Builder::spawn_unchecked_::{{closure}}
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:537:30
>   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
>   13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
>   14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
>   15: std::sys::pal::unix::thread::Thread::new::thread_start
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/pal/unix/thread.rs:108:17
>   16: <unknown>
>   17: clone
> ```

Builder has created a folder called `.gnome-builder` somewhere in your projects folder. Could you please run `.gnome-builder/projects/resources/install/host/libexec/resources/resources-processes -o -r` in your projects folder and send me the output?

**Comment by jojo2357** [comment]
It won't run, but neither will `resources` it complains about `'GLIBC_2.39' not found` which i am 100% sure is because this is Ubuntu 22.04

also the path was `.gnome-builder/projects/resources/flatpak/staging/x86_64-swap-columns/files/libexec/resources` which i found with `find`

**Comment by nokyan** [comment]
> It won't run, but neither will `resources` it complains about `'GLIBC_2.39' not found` which i am 100% sure is because this is Ubuntu 22.04
> 
> also the path was `.gnome-builder/projects/resources/flatpak/staging/x86_64-swap-columns/files/libexec/resources` which i found with `find`

Oh, that's quite unfortunate. Does prod Resources from Flathub run?

**Comment by jojo2357** [comment]
I can run it from flatpak and thru builder just not from cli (or at least idk how)

**Comment by nokyan** [comment]
Can you run `ldd --version`?

**Comment by jojo2357** [comment]
`Ubuntu GLIBC 2.35-0ubuntu3.8`

**Comment by nokyan** [comment]
It's odd that prod Resources runs, I didn't change anything related to libc since then I believe. :/
I'll check it out in a VM tomorrow.

**Comment by jojo2357** [comment]
Prod runs fine from builder, i didnt check if prod runs from cli but i highly doubt it.

This branch runs in builder, I just can't run your command since, pursuant to the last point, it wont run from cli

**Comment by jojo2357** [comment]
Color me a big fat liar...main doesnt build anymore. It definitely used to on my machine.

**Comment by jojo2357** [comment]
Git bisect blames `c7f3a5e3469d01d473d7f6eaec22a1b90af824da` for my error.

**Comment by jojo2357** [comment]
Okay I patched `adw` and `libc` back to pre `c7f3a5` and it looks GREAT

**Comment by jojo2357** [comment]
I started up a very memory-hungry application and now I know what programs got swapped out and how much total mem I could free by killing them.

Only other suggestion is to add the option for a `swap` + `mem` column, or `total mem` i guess. I can sort by one or the other but I want the sum (for hopefully obvious reasons)

**Comment by jojo2357** [comment]
An example:

![image](https://github.com/user-attachments/assets/0a91e062-8aa5-4cef-aa96-e3013bef6122)

It would be insane if DataGrip managed less memory than libreoffice or lollypop, but in reality it is just mostly swapped out

**Comment by nokyan** [comment]
> An example:
> 
> ![image](https://private-user-images.githubusercontent.com/66704796/378285598-0a91e062-8aa5-4cef-aa96-e3013bef6122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzQzMDYsIm5iZiI6MTcyOTUzNDAwNiwicGF0aCI6Ii82NjcwNDc5Ni8zNzgyODU1OTgtMGE5MWUwNjItOGFhNS00Y2VmLWFhOTYtZTMwMTNiZWY2MTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE4MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMjE0OWIyYmM5MThmMGQ4MjI5OWI4N2NmODI4NWM3MWQ2NWQ1NGEwMTFjNjQ5YzI3MDY0NjhjMTMzNzQ2YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3maS2VJ2AgaiDq9F17YbNNweg4lAdLqQPFXqK7Tagrc)
> 
> It would be insane if DataGrip managed less memory than libreoffice or lollypop, but in reality it is just mostly swapped out

I'm not sure, I don't want to have too many columns if you know what I mean and I also pledged to not introduce any new translatable strings until the next release. Maybe I'll include it later.

**Comment by jojo2357** [comment]
> I'm not sure, I don't want to have too many columns if you know what I mean

I see the sum as crucial, otherwise i can sort by resident, by swap, but not both so I would have to check both sorts to see the culprit of my high mem + swap usage

> I also pledged to not introduce any new translatable strings until the next release. Maybe I'll include it later.

Later is better than never for sure. Maybe kick the whole can down the road?

**Comment by nokyan** [comment]
> I see the sum as crucial, otherwise i can sort by resident, by swap, but not both so I would have to check both sorts to see the culprit of my high mem + swap usage

Yeah, makes sense.

> Later is better than never for sure. Maybe kick the whole can down the road?

We don't have to, I can merge the swap column since it doesn't introduce any new translation strings as "Swap" has already been translated. I can implement the column for combined usage for next version.

**Comment by nokyan** [comment]
I've pushed the combined memory usage column to the `combined-memory-column` branch. Do you mind checking it out?
