### ISSUE TITLE
More information about Device

### ISSUE THREAD

**Issue by cantalupo555** [nokyan/resources#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

I have a suggestion.
Would it be possible to add the total writing and reading of the Device?
Thanks!

**Comment by nokyan** [comment]
Hi,
I don't know whether Linux exposes this, I'll look into it.

**Comment by cantalupo555** [comment]
Maybe the command can help you:
`cat /proc/diskstats`

Contains detailed information about the read and write activities of the system's disk devices.

**Comment by cantalupo555** [comment]
Exemples:
Vitals (Gnome extension)
https://github.com/corecoding/Vitals
![image](https://github.com/nokyan/resources/assets/12485871/5e2b9568-288b-4a93-a39f-b7125ada16c9)

System Monitoring Center (Dead project)
https://github.com/hakandundar34coding/system-monitoring-center
![image](https://github.com/nokyan/resources/assets/12485871/dc6625c0-85de-42a7-b72a-3b820ab29ac9)
