### ISSUE TITLE
Error on Debian: "thread 'main' panicked at src/ui/window.rs:209:71"

### ISSUE THREAD

**Issue by Jachimo** [nokyan/resources#23]
I attempted to run Resources on a Debian system, kernel 5.10.191-1 (2023-08-16) x86_64 GNU/Linux.

Flatpak was freshly installed. (I tested one other Flatpak app, VLC, just to make sure it was working and it was fine.)

I installed Resources directly from Flathub with `flatpak install flathub net.nokyan.Resources`. No errors or any indication of problems was given.

But, every time I go to start Resources (by running `flatpak run net.nokyan.Resources`), I get a series of errors concluding with the following:

```
 DEBUG resources::application::imp > GtkApplication<Application>::activate
thread 'main' panicked at src/ui/window.rs:209:71:
called `Result::unwrap()` on an `Err` value: IO error while reading marker: failed to fill whole buffer

Caused by:
    failed to fill whole buffer
```
(See [resources-error.log](https://github.com/nokyan/resources/files/12907984/resources-error.log))

Resources opens, but the window is mostly empty and there's no content. (See screenshot.)

Happy to do more testing or gather further information if desired. Looks like a neat project, but I'm not too familiar with Flatpak or how to debug what's going on.

![resources-screen](https://github.com/nokyan/resources/assets/30067248/25f1a628-7af3-4f0d-808b-f2f61b96e008)

**Comment by nokyan** [comment]
Hi! Thanks for raising the issue. This is a known problem (#14) and will be fixed with the release of Resources 1.1 tomorrow (hopefully). For the meantime, you can install libadwaita on your device using your native package manager, for Debian that can be done with `sudo apt-get install libadwaita-1-0`, this will fix the issue.
