### ISSUE TITLE
Add Battery Graph

### ISSUE THREAD

**Issue by 6543** [nokyan/resources#247]
As i could not find an issue beside the todo mentioned at the readme (https://github.com/nokyan/resources?tab=readme-ov-file#to-do)

Here i create an issue to chat about it :)

---

I suggest the crate https://lib.rs/crates/starship-battery, that's at least what i use for my batmon ( https://github.com/6543/batmon )

**Comment by nokyan** [comment]
Hi, thanks for the issue.
![image](https://github.com/nokyan/resources/assets/20604611/65e20910-5899-42e7-b45c-4e1f8fe849c9)
How about that? (I don't know why manufacturer and model name are like this, I think this is a specific issue with my notebook)

**Comment by nokyan** [comment]
> Hi, the battery page is not showing up for me and there's an error in the logs.
> ❯ RUST_BACKTRACE=1 resources
> 
> thread 'main' panicked at src/ui/window.rs:772:22: called `Option::unwrap()` on a `None` value stack backtrace: 0: rust_begin_unwind 1: core::panicking::panic_fmt 2: core::panicking::panic 3: core::option::unwrap_failed 4: core::option::Option::unwrap at /usr/src/debug/rust/rustc-1.78.0-src/library/core/src/option.rs:933:21 5: resources::ui::window::MainWindow::refresh_battery_pages at ./src/ui/window.rs:769:31 6: resources::ui::window::MainWindow::refresh_ui at ./src/ui/window.rs:523:9 7: resources::ui::window::MainWindow::periodic_refresh_all::{{closure}} at ./src/ui/window.rs:568:13 8: resources::ui::window::MainWindow::setup_widgets::{{closure}} at ./src/ui/window.rs:333:41 9: glib::main_context_futures::::spawn_local_with_priority::{{closure}} at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.19.7/src/main_context_futures.rs:569:24 10: <glib::main_context_futures::FutureWrapper as core::future::future::Future>::poll 11: glib::main_context_futures::TaskSource::poll::{{closure}}::{{closure}} at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.19.7/src/main_context_futures.rs:247:25 12: core::ops::function::FnOnce::call_once at /usr/src/debug/rust/rustc-1.78.0-src/library/core/src/ops/function.rs:250:5 13: <core::panic::unwind_safe::AssertUnwindSafe as core::ops::function::FnOnce<()>>::call_once at /usr/src/debug/rust/rustc-1.78.0-src/library/core/src/panic/unwind_safe.rs:272:9 14: std::panicking::try::do_call at /usr/src/debug/rust/rustc-1.78.0-src/library/std/src/panicking.rs:552:40 15: std::panicking::try at /usr/src/debug/rust/rustc-1.78.0-src/library/std/src/panicking.rs:516:19 16: std::panic::catch_unwind at /usr/src/debug/rust/rustc-1.78.0-src/library/std/src/panic.rs:146:14 17: glib::main_context_futures::TaskSource::poll::{{closure}} at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.19.7/src/main_context_futures.rs:246:31 18: glib::main_context::::with_thread_default at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.19.7/src/main_context.rs:154:12 19: glib::main_context_futures::TaskSource::poll at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.19.7/src/main_context_futures.rs:238:9 20: glib::main_context_futures::TaskSource::dispatch at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.19.7/src/main_context_futures.rs:74:34 21: 22: 23: g_main_context_iteration 24: g_application_run 25: gio::application::ApplicationExtManual::run_with_args at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.5/src/application.rs:29:13 26: gio::application::ApplicationExtManual::run at ./build/cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.5/src/application.rs:22:9 27: resources::application::Application::run at ./src/application.rs:224:9 28: resources::gui::main at ./src/gui.rs:43:5 29: core::ops::function::FnOnce::call_once at /usr/src/debug/rust/rustc-1.78.0-src/library/core/src/ops/function.rs:250:5 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. thread '' panicked at src/ui/window.rs:558:44: called `Result::unwrap()` on an `Err` value: RecvError stack backtrace: 0: rust_begin_unwind 1: core::panicking::panic_fmt 2: core::result::unwrap_failed 3: core::result::Result<T,E>::unwrap at /usr/src/debug/rust/rustc-1.78.0-src/library/core/src/result.rs:1077:23 4: resources::ui::window::MainWindow::periodic_refresh_all::{{closure}}::{{closure}} at ./src/ui/window.rs:558:29 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 
> ```shell
> ls /sys/class/power_supply/
> ACAD@  BAT1@
> ```

Thanks for reporting the crash, can you run Resources with `RUST_LOG=resources=debug` set and send me the full logs?

**Comment by awumii** [comment]
<details>
❯ LC_ALL=C RUST_LOG=resources=debug resources  
  
 DEBUG resources::utils > Not running as Flatpak
 INFO  resources::application > Resources (net.nokyan.Resources.Devel)
 INFO  resources::application > Version: 1.4.0-8ac4252 (Devel)
 INFO  resources::application > Datadir: /usr/local/share/resources
 INFO  resources::application > You are running a development version of Resources, things may be slow or break!
 DEBUG resources::utils::memory > Memory information obtained using udevadm
 DEBUG resources::utils::app    > Detecting installed applications…
 DEBUG resources::utils::app    > The following locales will be used for app names and descriptions: ["pl_PL.UTF-8", "pl_PL", "pl", "C"]
 DEBUG resources::utils::app    > Detected 175 applications
 DEBUG resources::utils::pci    > Parsing pci.ids…
 DEBUG resources::utils::pci    > Successfully parsed pci.ids
 DEBUG resources::utils::gpu    > Found GPU "AMD Radeon Graphics (Cezanne [Radeon Vega Series / Radeon Vega Mobile Series])" (PCI slot: 0000:06:00.0 · PCI ID: 1002:1638 · Category: AMD)
 DEBUG resources::utils::gpu::nvidia > Successfully connected to NVML
 DEBUG resources::utils::gpu         > Found GPU "NVIDIA GeForce RTX 3050 Laptop GPU" (PCI slot: 0000:01:00.0 · PCI ID: 10de:25a2 · Category: NVIDIA)
 DEBUG resources::utils::cpu         > CPU temperature sensor located at /sys/class/hwmon/hwmon5/temp1_input (zenpower)
 WARN  resources::ui::window         > Unable to update battery at /sys/class/power_supply/BAT1, reason: No such file or directory (os error 2)
 DEBUG resources::ui::window         > A drive has been added (or turned visible): /sys/block/nvme0n1
 DEBUG resources::ui::window         > A drive has been added (or turned visible): /sys/block/nvme1n1
 DEBUG resources::ui::window         > A network interface has been added (or turned visible): /sys/class/net/wlp4s0
 DEBUG resources::ui::window         > A network interface has been added (or turned visible): /sys/class/net/enp3s0
 DEBUG resources::ui::window         > A battery has been added: /sys/class/power_supply/BAT1
thread 'main' panicked at src/ui/window.rs:772:22:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/ui/window.rs:558:44:
called `Result::unwrap()` on an `Err` value: RecvError
</details>

I see a no such file error, so here's the contents of BAT1 in case it's useful:
```bash
❯ ls /sys/class/power_supply/BAT1/
alarm           charge_full         current_now  hwmon1/       power/         status      type                voltage_now
capacity        charge_full_design  cycle_count  manufacturer  present        subsystem@  uevent
capacity_level  charge_now          device@      model_name    serial_number  technology  voltage_min_design
```

**Comment by nokyan** [comment]
> ❯ LC_ALL=C RUST_LOG=resources=debug resources
> 
> DEBUG resources::utils > Not running as Flatpak INFO resources::application > Resources (net.nokyan.Resources.Devel) INFO resources::application > Version: 1.4.0-8ac4252 (Devel) INFO resources::application > Datadir: /usr/local/share/resources INFO resources::application > You are running a development version of Resources, things may be slow or break! DEBUG resources::utils::memory > Memory information obtained using udevadm DEBUG resources::utils::app > Detecting installed applications… DEBUG resources::utils::app > The following locales will be used for app names and descriptions: ["pl_PL.UTF-8", "pl_PL", "pl", "C"] DEBUG resources::utils::app > Detected 175 applications DEBUG resources::utils::pci > Parsing pci.ids… DEBUG resources::utils::pci > Successfully parsed pci.ids DEBUG resources::utils::gpu > Found GPU "AMD Radeon Graphics (Cezanne [Radeon Vega Series / Radeon Vega Mobile Series])" (PCI slot: 0000:06:00.0 · PCI ID: 1002:1638 · Category: AMD) DEBUG resources::utils::gpu::nvidia > Successfully connected to NVML DEBUG resources::utils::gpu > Found GPU "NVIDIA GeForce RTX 3050 Laptop GPU" (PCI slot: 0000:01:00.0 · PCI ID: 10de:25a2 · Category: NVIDIA) DEBUG resources::utils::cpu > CPU temperature sensor located at /sys/class/hwmon/hwmon5/temp1_input (zenpower) WARN resources::ui::window > Unable to update battery at /sys/class/power_supply/BAT1, reason: No such file or directory (os error 2) DEBUG resources::ui::window > A drive has been added (or turned visible): /sys/block/nvme0n1 DEBUG resources::ui::window > A drive has been added (or turned visible): /sys/block/nvme1n1 DEBUG resources::ui::window > A network interface has been added (or turned visible): /sys/class/net/wlp4s0 DEBUG resources::ui::window > A network interface has been added (or turned visible): /sys/class/net/enp3s0 DEBUG resources::ui::window > A battery has been added: /sys/class/power_supply/BAT1 thread 'main' panicked at src/ui/window.rs:772:22: called `Option::unwrap()` on a `None` value note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace thread '' panicked at src/ui/window.rs:558:44: called `Result::unwrap()` on an `Err` value: RecvError
> 
> I see a no such file error, so here's the contents of BAT1 in case it's useful:
> 
> ```shell
> ❯ ls /sys/class/power_supply/BAT1/
> alarm           charge_full         current_now  hwmon1/       power/         status      type                voltage_now
> capacity        charge_full_design  cycle_count  manufacturer  present        subsystem@  uevent
> capacity_level  charge_now          device@      model_name    serial_number  technology  voltage_min_design
> ```

Thanks, I think I found the issue. I'll push something to `battery` soon. :)

**Comment by nokyan** [comment]
I pushed a potential fix to `battery`, could you test it @awumii?

**Comment by awumii** [comment]
Thanks, its working now! Just some missing values.
![obraz](https://github.com/nokyan/resources/assets/29680081/6b4c08e3-5988-45e5-97e3-ae01f455bf9d)
