### ISSUE TITLE
Add rounded corners to graphs

### ISSUE THREAD

**Issue by 2nv2u** [nokyan/resources#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Current look:
![image-3_orig](https://github.com/nokyan/resources/assets/69992184/9689a45f-1202-403b-bb6d-0dc20d2569a3)

Concept look:
![image-3_rounded](https://github.com/nokyan/resources/assets/69992184/417cab77-06bb-4cac-a21e-2979170b59cb)

### Describe alternatives you've considered

Margin graph (labels) need attention, feel cramped

### Additional context

Nice work otherwise, should replace the default system monitor for sure...

**Comment by nokyan** [comment]
Hi,
looks good, I'll try to implement some time in the future.

**Comment by 2nv2u** [comment]
Hi Nokyan,

Your current implementation looks nice but it does feel off a little (consistency) when it comes to the styling of the rest of the gnome shell.

My suggestion would be to add the text in the boxes like in my example but adding a margin to cover the complete area so that when hovering the resources it will just make the whole box lighter (or darker), essentially having the exact same look as the [top time view](https://help.ubuntu.com/stable/ubuntu-help/figures/shell-appts.png) but with subtle different colors depending on the resource like you already did.

**Comment by nokyan** [comment]
> Hi Nokyan,
> 
> Your current implementation looks nice but it does feel off a little (consistency) when it comes to the styling of the rest of the gnome shell.
> 
> My suggestion would be to add the text in the boxes like in my example but adding a margin to cover the complete area so that when hovering the resources it will just make the whole box lighter (or darker), essentially having the exact same look as the [top time view](https://help.ubuntu.com/stable/ubuntu-help/figures/shell-appts.png) but with subtle different colors depending on the resource like you already did, pay attention to the overall margins of these boxes as well, these are bigger in all other UI elements in gnome shell.
> 
> ![concept_resources](https://private-user-images.githubusercontent.com/69992184/402908134-56e1c256-fd46-44d4-9a69-8a42936f4887.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NTU4OTIsIm5iZiI6MTczNjg1NTU5MiwicGF0aCI6Ii82OTk5MjE4NC80MDI5MDgxMzQtNTZlMWMyNTYtZmQ0Ni00NGQ0LTlhNjktOGE0MjkzNmY0ODg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDExNTMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzhhMzVlYjMxODBkYzM4ODU1ODRhOGQ2YmM3ZmQ3NTY1ZTY4NDkwZGZlNDBlMjJmYWJiMzA3MWM1MTcxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.avh95ITa9EcVk2mrmeFpjOI9YUF0iAUKnCxqZwST7-k) Remark: would be nice if the actual graph would cover the whole box and start at the bottom, so essentially also no margin like the graphs in the view itself.

Hi, thanks for the suggestion.
I like it, though I'm not sure how to implement that. I'll try to get it done.
