### ISSUE TITLE
GPU utilization over 100%

### ISSUE THREAD

**Issue by TheRsKing** [nokyan/resources#261]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

![Bildschirmfoto vom 2024-06-23 19-13-10](https://github.com/nokyan/resources/assets/130909958/59fe8b99-8e78-4d64-a65b-123c5018fef9)

### Environment

```markdown
1.5.0
Flatpak
opensuse Aeon
AMD CPU & GPU
```

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I'm gonna release a hotfix including this in a couple days. :)

**Comment by TheRsKing** [comment]
Oh wow, that was fast, thanks!

**Comment by TheRsKing** [comment]
> Hi, thanks for the issue. I'm gonna release a hotfix including this in a couple days. :)

I don't want to be stressful or intrusive in any way, I'm just curious; when is the hotfix expected to arrive?

**Comment by nokyan** [comment]
> > Hi, thanks for the issue. I'm gonna release a hotfix including this in a couple days. :)
> 
> I don't want to be stressful or intrusive in any way, I'm just curious; when is the hotfix expected to arrive?

No worries, I haven't been to well the last few days, but I think sometime next week. :)

**Comment by nokyan** [comment]
> > Hi, thanks for the issue. I'm gonna release a hotfix including this in a couple days. :)
> 
> I don't want to be stressful or intrusive in any way, I'm just curious; when is the hotfix expected to arrive?

Hotfix is released :)
