### ISSUE TITLE
Logitech mouse and keyboard battery info is missing

### ISSUE THREAD

**Issue by meybonomme** [nokyan/resources#265]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

There is no useful information about Logitech mouse and keyboard batteries

### Expected Behavior

If the batteries are visible in the selection, they should provide useful information.

### Environment

```markdown
App version 1.5.0
Flatpak
Fedora 40
```
![Screenshot from 2024-06-28 02-40-01](https://github.com/nokyan/resources/assets/147217565/27fcc50c-d530-4dff-a3f2-e15dd8a2dcdf)
![Screenshot from 2024-06-28 02-39-33](https://github.com/nokyan/resources/assets/147217565/65fd133e-3255-42d9-a291-349eab4a7867)

**Comment by jojo2357** [comment]
Ditto

![image](https://github.com/nokyan/resources/assets/66704796/e58e4f4b-401f-4710-8ec8-d62f27410281)

`tree /sys/class/power_supply/hidpp_battery_3`
```
.
├── capacity_level
├── device -> ../../../0003:046D:405E.0016
├── hwmon8
│   ├── device -> ../../hidpp_battery_3
│   ├── name
│   ├── power
│   │   ├── async
│   │   ├── autosuspend_delay_ms
│   │   ├── control
│   │   ├── runtime_active_kids
│   │   ├── runtime_active_time
│   │   ├── runtime_enabled
│   │   ├── runtime_status
│   │   ├── runtime_suspended_time
│   │   └── runtime_usage
│   ├── subsystem -> ../../../../../../../../../../../class/hwmon
│   └── uevent
├── manufacturer
├── model_name
├── online
├── power
│   ├── async
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── runtime_active_kids
│   ├── runtime_active_time
│   ├── runtime_enabled
│   ├── runtime_status
│   ├── runtime_suspended_time
│   ├── runtime_usage
│   ├── wakeup
│   ├── wakeup_abort_count
│   ├── wakeup_active
│   ├── wakeup_active_count
│   ├── wakeup_count
│   ├── wakeup_expire_count
│   ├── wakeup_last_time_ms
│   ├── wakeup_max_time_ms
│   └── wakeup_total_time_ms
├── powers -> ../../../0003:046D:405E.0016
├── scope
├── serial_number
├── status
├── subsystem -> ../../../../../../../../../../class/power_supply
├── type
├── uevent
└── wakeup37
    ├── active_count
    ├── active_time_ms
    ├── device -> ../../hidpp_battery_3
    ├── event_count
    ├── expire_count
    ├── last_change_ms
    ├── max_time_ms
    ├── name
    ├── prevent_suspend_time_ms
    ├── subsystem -> ../../../../../../../../../../../class/wakeup
    ├── total_time_ms
    ├── uevent
    └── wakeup_count
```

**Comment by nokyan** [comment]
Hi, thanks for the issue and for the `tree` output.
Some Logitech mice apparently do at least offer the current battery charge as info. I'll implement a fix, which will make Resources ignore batteries that don't at least have the current battery charge in SysFS. :)

**Comment by meybonomme** [comment]
In my opinion, it should be limited to just showing the laptop battery information. However, Recources is more of a system monitoring and management tool than for managing external devices. Too many options make an app bloated, especially if they don't add significant value.

Most of the batteries of external devices do not give any other information than the charge level anyway (even that only roughly), especially if it is a non-rechargeable battery. Moreover, GNOME Setting shows the battery level of external devices well enough, and GNOME shell also sends a notification when the battery level is too low:

![Screenshot from 2024-06-29 22-32-15](https://github.com/nokyan/resources/assets/147217565/f8971c05-1da1-4d5b-96c3-b25ac6c2a7bc)

**Comment by nokyan** [comment]
> In my opinion, it should be limited to just showing the laptop battery information. However, Recources is more of a system monitoring and management tool than for managing external devices. Too many options make an app bloated, especially if they don't add significant value.
> 
> Most of the batteries of external devices do not give any other information than the charge level anyway (even that only roughly), especially if it is a non-rechargeable battery. Moreover, GNOME Setting shows the battery level of external devices well enough, and GNOME shell also sends a notification when the battery level is too low:
> 
> ![Screenshot from 2024-06-29 22-32-15](https://private-user-images.githubusercontent.com/147217565/344428838-f8971c05-1da1-4d5b-96c3-b25ac6c2a7bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzA4MDgsIm5iZiI6MTcxOTczMDUwOCwicGF0aCI6Ii8xNDcyMTc1NjUvMzQ0NDI4ODM4LWY4OTcxYzA1LTFkYTEtNGQ1Yi05NmMzLWIyNWFjNmMyYTdiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNjU1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODMxN2Y0MDkwMTNjMTc5NTQyZWRkYmJhYjdlNTE4M2Y0YzkxY2Q1YWJhN2I5ODEwODFkYmFkODdkNmYxMzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.36p171Mzp427S6BfGQa8X6a3q4QJOQsuUoOkygh7OmE)

Yeah, that's a good point as well. I'll think about it, maybe others can voice their opinion here too

**Comment by nokyan** [comment]
I've pushed a change to `battery-fixes`: non-notebook batteries will be ignored. I'd appreciate if you could test it :)

**Comment by meybonomme** [comment]
How can I test it? I'm currently using the Flathub version.

**Comment by nokyan** [comment]
> How can I test it? I'm currently using the Flathub version.

You'd have to build Resources yourself. It should work like this:

```sh
git clone https://github.com/nokyan/resources.git
cd resources
git checkout battery-fixes
flatpak install org.gnome.Sdk//46 org.freedesktop.Sdk.Extension.rust-stable//23.08 org.gnome.Platform//46 org.freedesktop.Sdk.Extension.llvm18//23.08
flatpak-builder --user flatpak_app build-aux/net.nokyan.Resources.Devel.json
flatpak-builder --run flatpak_app build-aux/net.nokyan.Resources.Devel.json resources```

You'd neet Rust and flatpak-builder installed.
Alternatively, if you don't want to do that, I'd also appreciate if you could tell me what Resources says in the "Device" entry of your normal laptop battery. :)

**Comment by meybonomme** [comment]
If I have a bit more time, I can test. My laptop battery info:

![pilt](https://github.com/nokyan/resources/assets/147217565/da8f0e05-109c-4186-a4e8-a38b911f4df7)

**Comment by nokyan** [comment]
> If I have a bit more time, I can test. My laptop battery info:
> 
> ![pilt](https://private-user-images.githubusercontent.com/147217565/346289298-da8f0e05-109c-4186-a4e8-a38b911f4df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyOTc5MjUsIm5iZiI6MTcyMDI5NzYyNSwicGF0aCI6Ii8xNDcyMTc1NjUvMzQ2Mjg5Mjk4LWRhOGYwZTA1LTEwOWMtNDE4Ni1hNGU4LWEzOGI5MTFmNGRmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQyMDI3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODk0M2Y5ZTdmYjg4NTI4YjM5ZmE1YzY1M2I2OTkzYmY5MDgzNDE3ZjQ0MWZkNzIyOWQzNDU0NjQzN2MxMTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U1rvkAi2HkV1Y4QcYhPwsNBPA7-NCUBSLXAnDzJXdWY)

Thanks! I'd like to release 1.5.1 with this fix tomorrow, so I'll merge the branch since your battery should be detected as a laptop battery with the new fix.

**Comment by meybonomme** [comment]
I can confirm that Resources now only shows the laptop battery.
