### ISSUE TITLE
Power usage missing on RX 580

### ISSUE THREAD

**Issue by awumii** [nokyan/resources#270]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Current power usage is not shown for AMD Radeon RX 580

### Expected Behavior

Show current power usage like in nvtop

### Environment

```markdown
Resources 1.5
Arch Linux 6.9.7
```

### Anything else?

![obraz](https://github.com/nokyan/resources/assets/29680081/9f0f7350-cd0d-41d5-91aa-bdecb181095f)
![obraz](https://github.com/nokyan/resources/assets/29680081/12317705-0fd3-48fb-9f29-d7232e32b5bc)

❯ tree /sys/class/drm/card0/device/hwmon/
/sys/class/drm/card0/device/hwmon/
└── hwmon2
    ├── device -> ../../../0000:05:00.0
    ├── fan1_enable
    ├── fan1_input
    ├── fan1_max
    ├── fan1_min
    ├── fan1_target
    ├── freq1_input
    ├── freq1_label
    ├── freq2_input
    ├── freq2_label
    ├── in0_input
    ├── in0_label
    ├── name
    ├── power
    │   ├── autosuspend_delay_ms
    │   ├── control
    │   ├── runtime_active_time
    │   ├── runtime_status
    │   └── runtime_suspended_time
    ├── power1_cap
    ├── power1_cap_default
    ├── power1_cap_max
    ├── power1_cap_min
    ├── power1_input
    ├── power1_label
    ├── pwm1
    ├── pwm1_enable
    ├── pwm1_max
    ├── pwm1_min
    ├── subsystem -> ../../../../../../class/hwmon
    ├── temp1_crit
    ├── temp1_crit_hyst
    ├── temp1_input
    ├── temp1_label
    └── uevent

**Comment by nokyan** [comment]
Hi, thanks for the issue and thanks for the `tree` output. 
Do you know whether it worked before? Because I remember it working for my integrated AMD GPU of my notebook, just without the power cap (I assume iGPUs don't have one).

**Comment by awumii** [comment]
I think it worked the same way as you described on my AMD laptop, but I don't have it anymore. This is a new PC I built a few days ago, without an integrated GPU.

**Comment by nokyan** [comment]
I've pushed a fix to the `amd-gpu-fix` branch. Do you mind trying it out? It seems to work for me

**Comment by awumii** [comment]
![image](https://github.com/nokyan/resources/assets/29680081/176d2daf-1ce8-44f3-82f4-5d0a819775fd)
Confirmed to be working fine!

**Comment by nokyan** [comment]
Perfect! Closing this then. :)
