### ISSUE TITLE
"Search", "Show App Information" and "Show Process Information" button tooltips are not translatable

### ISSUE THREAD

**Issue by Tuba2** [nokyan/resources#279]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Whenever I hover the cursor above the "Search", "Show App Information" and "Show Process Information" buttons, I get tooltips in English, even though I'm using the Brazilian Portuguese translation, which is already complete.

### Expected Behavior

I expected the tooltips to appear in Brazilian Portuguese, but I looked into the POT file and couldn't find translatable strings for these buttons.

### Steps To Reproduce

https://github.com/nokyan/resources/assets/82492785/931b52c9-8fe8-4cd6-947e-11c8aab59a69

### Environment

```markdown
Program Version 1.5.1
Package type: Flatpak
System: Fedora Linux 40 (Workstation Edition)
```

**Comment by nokyan** [comment]
Hi, thanks for the issue.
That's pretty odd, I'll look into it. Hopefully it's just a translate=yes tag in the .ui files.
