### ISSUE TITLE
Inserting USB Drive places new entry at *bottom* of list rather than at the end of the drives

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#283]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When inserting a new drive, the entry on the sidebar is at the bottom

### Expected Behavior

I expected it to be at the end of the drives

### Steps To Reproduce

Open resources and then insert a USB drive

### Environment

```markdown
Likely not relevant
```

**Comment by nokyan** [comment]
Hi, thanks for the issue.
Do you mind testing out the fix in the [`sidebar-ordering-fix`](https://github.com/nokyan/resources/tree/sidebar-ordering-fix) branch?

**Comment by jojo2357** [comment]
works in [`25a1b56`](https://github.com/nokyan/resources/commit/25a1b56f22590f95332b526f3757c7c55c5d35b0)
