### ISSUE TITLE
Show some message when no tab is focused

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When removing the drive that you are looking at, you get left with a blank screen (sidebar is still there)

### Describe the solution you'd like

Show a message like "drive was removed, please select smthn to look at"

### Describe alternatives you've considered

Auto select a new drive to open? could be confusing if the drive is only temporarily dc'd

**Comment by nokyan** [comment]
Hi,
I'm not quite sure what you mean, Resources jumps back to the Applications view if the drive whose page you are viewing gets disconnected. Could you maybe share a video of the issue? :)

**Comment by jojo2357** [comment]
I disagree with that assessment. 

Here are my steps:
 - Set settings like so:
![image](https://github.com/nokyan/resources/assets/66704796/6643f917-80d8-4773-a564-cbf19188b728)
 - Open resources
 - Have a flash drive plugged in (order of this and prev no factor)
 - eject via gnome-disks
 - observe
![image](https://github.com/nokyan/resources/assets/66704796/8a18cf2d-40fc-499b-a2bc-8e859f4d8223)

Noticed issue when i built from source then noticed it on flatpak build.

**Comment by nokyan** [comment]
Thanks, I can reproduce it now. I'll look into it.
