### ISSUE TITLE
Add support for applications with absolute path icons

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

All of my Jetbrains IDE's do not show up with an icon. These are my only apps that have svg Icons as well.

### Describe the solution you'd like

Show the icons

### Describe alternatives you've considered

I tried to debug it, and I couldnt figure out if gio's Icons were to blame

### Additional context

`.desktop`
```
[Desktop Entry]
Name=IntelliJ IDEA Ultimate 2024.1.4
Exec="/home/jojo2357/JetBrains/intellij-idea-ultimate/bin/idea.sh" %u
Version=1.0
Type=Application
Categories=Development;IDE;
Terminal=false
Icon=/home/jojo2357/JetBrains/intellij-idea-ultimate/bin/idea.svg
Comment=The Leading Java and Kotlin IDE
StartupWMClass=jetbrains-idea
StartupNotify=true
```

`.svg`
![idea](https://github.com/nokyan/resources/assets/66704796/9f033941-bc8c-4b11-b9d9-2db96b19bfd4)

**Comment by nokyan** [comment]
Hi,
could you give Resources permission to read your home folder and try again? I feel like this has got something to do with that.

**Comment by jojo2357** [comment]
How am I supposed to do that? perms on the svg are `664`

**Comment by nokyan** [comment]
> How am I supposed to do that? perms on the svg are `664`

Oh, I meant Flatpak permissions. :)
You can use Flatseal to change Resources' permissions. Toggle it like that:
![image](https://github.com/nokyan/resources/assets/20604611/634ea6fd-f830-4073-b2c7-b49f0a6b7664)

**Comment by jojo2357** [comment]
![image](https://github.com/nokyan/resources/assets/66704796/6b41317f-9701-4d93-a56c-a819a2d1b4d8)
Neither of these worked (even after restarting resources)

**Comment by jojo2357** [comment]
I solved it. Opening a pr to continue discussion. Also changing issue name to reflect my results
