### ISSUE TITLE
Add debug prints for app detection

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I find that I sometimes am trying to figure out what is going wrong with app detection. (in my case it was that there were two `.desktop` files for the same execuatable, and the wrong (and bad) one was being used and causing the problem.

### Describe the solution you'd like

It would be very nice to have debug prints that explain which `.desktops` were parsed, and what the pertinent values were.

It would be best to have an option to print out the detection results so I can know why a certain process was detected to be a specific app.

**Comment by nokyan** [comment]
Hi, thanks for the issue.
Sure, I can do that. I was thinking about other useful debug statements anyways, this sounds like a good idea. :)

**Comment by nokyan** [comment]
I've added some more debug statements, feel free to give feedback in the PR #305 :)
