### ISSUE TITLE
App Children Not Accounted For

### ISSUE THREAD

**Issue by jojo2357** [nokyan/resources#299]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

For some apps, in particular `dolphin-emu` and `proton-mail`, the children spawned either from the main app, or from the launcher, are not having the same CGroup. Instead, they have the `org.gnome.Shell` CGroup.

### Expected Behavior

Children of a detected app will be counted as part of the app, unless the child is clearly another app.

### Steps To Reproduce

I installed the `proton-mail` deb, and built `dolphin-emu` from source.

### Environment

```markdown
1.5.1, Pop!_OS 22.04 LTS, GNOME 42.9
```

### Anything else?

Mission center, which I think uses parental inheritance, is able to find the children of `proton-mail`, and resources does not detect `dolphin-emu` as an app, despite being in the right cgroup (i think? its in `dolphin-emu`)

**Comment by nokyan** [comment]
Hi, thanks for the issue, I'll look into it and your PR. :)
