### ISSUE TITLE
If power_now is missing, calculate it from voltage_now and current_now

### ISSUE THREAD

**Issue by Excigma** [nokyan/resources#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It appears that the power usage is found from the `power_now` sysfs field: https://github.com/nokyan/resources/blob/24a5497af561edf9300fbbf32ff1cc011d9f352c/src/utils/battery.rs#L292

My system is missing this field so Resources does not show the power usage chart, however other battery monitoring tools such as [Vitals](https://github.com/corecoding/Vitals) and `upower` still work

### Describe the solution you'd like

In my sysfs, `voltage_now` and `current_now` exist - perhaps it is possible to multiply them together to calculate power usage?
![image](https://github.com/user-attachments/assets/f0f1d2a0-625c-488b-b0e3-6369996435b3)

### Additional context

Thank you very much for maintaining this excellent app!

unrelated, but there are a couple of small typos: https://github.com/nokyan/resources/blob/main/src/utils/battery.rs#L311C39-L311C48 https://github.com/nokyan/resources/blob/main/src/utils/battery.rs#L252C47-L252C58

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I've seen other instances of voltage_now and current_now existing instead of power_now but I was kinda hesitant to implement that because I don't know how accurate those are, my notebook has just power_now.
I'll implement that later in a branch, I'd appreciate it if you could test it and see whether the calculations make sense. :)

**Comment by nokyan** [comment]
I've pushed a branch called `voltage-current-power`, could you test that?

**Comment by Excigma** [comment]
The power usage graph didn't show up for me when I tried the branch - I tried adding a `print!("klsdsdlf")` into both `power_usage()` and `power_usage_from_voltage_and_current()`, however, only the one in `power_usage()` was called.

I messed around and got it to work with the code below, however, I'm not particularly good at Rust so there may be a better way to do it

```rs
pub fn power_usage(&self) -> Result<f64> {
    std::fs::read_to_string(self.sysfs_path.join("power_now"))
        .context("unable to parse power_now sysfs file")
        .and_then(|x| {
            x.trim()
                .parse::<usize>()
                .map(|microwatts| microwatts as f64 / 1_000_000.0)
                .context("unable to parse power_now sysfs file")
        })
        .or_else(|_| self.power_usage_from_voltage_and_current())
}
```

After this, the calculations appear to make sense - the values also scale with cpu load and brightness changing, thank you very much for this!

[Screencast from 2024-07-24 11-16-44.webm](https://github.com/user-attachments/assets/e4b1eed3-6ed2-4fab-b443-8864838c988b)

**Comment by Excigma** [comment]
Hmm, not too relevant to this issue but it seems like the graph is still labelled as "Power Usage" whilst my laptop is charging
