### ISSUE TITLE
Process priority and affinity 

### ISSUE THREAD

**Issue by awumii** [nokyan/resources#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I wish i could fully replace gnome-system-monitor with resources, but these are the two missing features, and the only reason i still keep gnome-system-monitor installed.

### Describe the solution you'd like

Show process priority and affinity, and allow changing it.

### Additional context

![obraz](https://github.com/user-attachments/assets/8b31a920-3719-4aa0-8241-94fcf33897e2)
![obraz](https://github.com/user-attachments/assets/cb12cc94-a515-49c6-9cca-18ebfa69a45d)

The only issue i see, is that resources does not have a right click action menu for managing processes, only buttons to show information and close the process on the bottom of the page, so i have no idea where these options should be placed.

**Comment by nokyan** [comment]
Hi, thanks for the issue.
It's on the to-do list. :)

**Comment by nokyan** [comment]
I'm currently implementing priority, do you think "Very High", "High", "Normal", "Low" and "Very Low" would be enough for the job? I'd prefer that over the very unintuitive niceness value between -19 and 20.

**Comment by awumii** [comment]
That would be enough for me, though GNOME's system monitor has this _nice_ menu for adjusting priority, while also showing an user-friendly description:
![obraz](https://github.com/user-attachments/assets/6b406bf6-e70f-4964-b793-cdba46829b43)

I think five presets is good enough, but some people may want more precise control.

**Comment by nokyan** [comment]
I believe I found a compromise: you can toggle, whether you want "simple" priorities or the real nicenesses in the new dialog.
![image](https://github.com/user-attachments/assets/cff8ebd1-c469-4d1d-aad0-e73545fe8edc)
![image](https://github.com/user-attachments/assets/abee75d1-19e1-452a-bbfc-1fbfcc7324c0)
![image](https://github.com/user-attachments/assets/d1933fda-a2b4-4994-91d1-9b1b8290697f)
(ignore the typo in the last screenshot)

**Comment by awumii** [comment]
Looks good!

**Comment by nokyan** [comment]
I think I'm done so far with the changes related to this issue, feel free to check out the `process-priority-affinity` branch! :)

**Comment by awumii** [comment]
Just tested it and it works fine!

**Comment by nokyan** [comment]
> But there should be a button to toggle all cpu threads

Done!

**Comment by awumii** [comment]
Actually, i noticed some weird behavior that i can only explain with a video.... 
https://youtu.be/Nqxt54VpA0k
I also tested this with stress-ng limited to one thread, and setting the process to only one cpu would limit that process to the selected cpu correctly. So it seems to only work with non multi-threaded processes?

**Comment by awumii** [comment]
I just compiled the branch with latest changes, and the button to select all currently only works as "toggle all on", so as you can see on the video above, i still have to manually click all the cpus, because by default they are all toggled on.

**Comment by nokyan** [comment]
I believe I have fixed both of your issues, could you test again? :)

**Comment by awumii** [comment]
Yes, it works properly now

**Comment by nokyan** [comment]
Nice, gonna merge then :)
