### ISSUE TITLE
Problems when resizing to min width

### ISSUE THREAD

**Issue by tronta** [nokyan/resources#31]
When minimizing the width, right side of window gets cut off.
[video.webm](https://github.com/nokyan/resources/assets/5135577/34146668-cbc1-4040-99c7-5a99d91fcac5)

**Comment by nokyan** [comment]
Thank you for submitting this issue! This seems to be because the ColumnView for processes requires a lot of space, especially when the user name or one of the translations like "Arbeitsspeicher" is quite long. It's on my to-do list. :)

**Comment by julianfairfax** [comment]
[This also affects mobile devices.](https://fosstodon.org/@julianfairfax/111228486410602538)
> > I'm not sure whether or not it works well on mobile Linux, like GNOME Usage does? Resizing the window on my laptop leads me to believe that it's adaptive, so it should work?

> Ok so, it runs, but it doesn't scale properly, so for example the edges of the info windows are cut off, the dropdown menu on the end process button is cut off, the ends of graphs are cut off.

> It also doesn't declare itself as a mobile-compatible application, so Phosh (which is like GNOME Shell for mobile devices) doesn't show it by default.

> I can open an issue for these things if you want. I'm not sure how easy they are to fix, but it shouldn't be too difficult.

**Comment by julianfairfax** [comment]
@nokyan since the MR was merged, should this be closed now? Either way, please also declare the app as supporting mobile devices, so it shows on mobile home screens.

**Comment by nokyan** [comment]
> @nokyan since the MR was merged, should this be closed now? Either way, please also declare the app as supporting mobile devices, so it shows on mobile home screens.

Oh yeah, sorry, I will. Thanks for the reminder. ^^

**Comment by julianfairfax** [comment]
> Either way, please also declare the app as supporting mobile devices, so it shows on mobile home screens.

This means you have to add `X-Purism-FormFactor=Workstation;Mobile;` to [`net.nokyan.Resources.desktop.in.in`](https://github.com/nokyan/resources/blob/main/data/net.nokyan.Resources.desktop.in.in).

**Comment by nokyan** [comment]
> This means you have to add `X-Purism-FormFactor=Workstation;Mobile;` to [`net.nokyan.Resources.desktop.in.in`](https://github.com/nokyan/resources/blob/main/data/net.nokyan.Resources.desktop.in.in).

Oh, I didn't know about that, I only knew about the appinfo stuff, thank you.

**Comment by nokyan** [comment]
![image](https://github.com/nokyan/resources/assets/20604611/1d42e7a1-b2b4-4556-a9d0-23e862b25324)
So I've released Resources 1.2.1 and it still shows that it only works on desktops, at least for me. I frankly don't know what else to do… 😅
I'll do some more research and see what other apps are doing, though I've used GNOME Software's `--show-metainfo` CLI option to display Resources' metainfo and it's recognized as mobile-friendly there.

**Comment by julianfairfax** [comment]
I don't know why it shows that. Maybe it will update. Either way though, it's not important. What's important is what I had you add to the desktop file. So now, when you have Resources installed on a phone running Phosh, the app will show in your app drawer (instead of hiding behind a show all apps button). Don't worry about the rest.
