### ISSUE TITLE
Some icons don't appear on "Applications" and "Processes"

### ISSUE THREAD

**Issue by pesader** [nokyan/resources#32]
The icons of some apps do not show up on "Applications" and "Processes" panels. This issue persists even when I give Resources permission to access my entire home directory, so I don't think it's an issue with permissions. I'm also using the default icon theme (Adwaita).

Here are some screenshots of how it looks:

| "Applications" panel | Application info |
|-|-|
|![image](https://github.com/nokyan/resources/assets/65264536/39c22fe4-9aa7-4973-836a-2ff4d1a87412) | ![image](https://github.com/nokyan/resources/assets/65264536/901e6331-9dad-43f0-998d-563dd2c32f81) |

Thank you for developing Resources, it's truly great! 📈 💻

**Comment by nokyan** [comment]
Hi, I'm glad you like Resources. These are user-wide (instead of system-wide) installed Flatpaks, right? I'll look into this, though it'S weird that it doesn't work even if you give Resources full read-access to your home directory. :/

**Comment by pesader** [comment]
Yes, they're all user-wide flatpaks, installed from the Flathub remote.

It seems that most of the apps whose icon is not showing up are running in the background (e.g. Calendar, Calculator, Smile, etc). Maybe that's the problem, somehow?

**Comment by TheRsKing** [comment]
> Hi, I'm glad you like Resources. These are user-wide (instead of system-wide) installed Flatpaks, right? I'll look into this, though it'S weird that it doesn't work even if you give Resources full read-access to your home directory. :/

I have exactly the same problem, also only with user-wide installed flatpaks.

**Comment by orowith2os** [comment]
Same here. Is Resources getting its XDG variables imported correctly, and translating them appropriately such that it can read the icon set installed by Flatpak?

**Comment by nokyan** [comment]
> Same here. Is Resources getting its XDG variables imported correctly, and translating them appropriately such that it can read the icon set installed by Flatpak?

Yeah, Resources reads XDG_DATA_DIRS successfully and uses that to find .desktop files. Resources also has read permissions for e.g. ~/.local/share/flatpak/exports/share/icons/hicolor/scalable/apps/, at least I can read files from there perfectly fine when being in Resources' container with `flatpak run --command="bash" net.nokyan.Resources`. :/

**Comment by TheRsKing** [comment]
are there any updates here?

**Comment by nokyan** [comment]
Nope, still haven't found the issue. Sorry.

**Comment by pesader** [comment]
I figured out what's happening! The problem is in the way that the `XDG_DATA_DIRS` is defined in the manifest. Originally we have:

`XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/usr/share:/run/host/share:/var/lib/flatpak/exports/share:~/.local/share/flatpak/exports/share:/var/lib/snapd/desktop`

When I replaced the `~` with the absolute path to my home directory I got all icons to show up, like so:

`XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/usr/share:/run/host/share:/var/lib/flatpak/exports/share:/var/home/pesader/.local/share/flatpak/exports/share:/var/lib/snapd/desktop`

| Before | After |
|-|-|
|![image](https://github.com/nokyan/resources/assets/65264536/08fb90ea-6da1-443d-b6d3-76e286e3447d)|![image](https://github.com/nokyan/resources/assets/65264536/d9c4e752-8f7c-4a59-ac95-a2d2166e8d91)|

I suppose that's because `~` is a shell expansion, which won't be interpreted correctly by flatpak. I tried replacing it with `$HOME` but it didn't work. I also checked the manifest of [Mission Center](https://flathub.org/apps/io.missioncenter.MissionCenter), but they use the same `~` in their definition of the `XDG_DATA_DIRS` variable and have the same problem of some icons not showing up.

Any way, at least for the time being, this is the workaround.

**Comment by nokyan** [comment]
> I figured out what's happening! The problem is in the way that the `XDG_DATA_DIRS` is defined in the manifest. Originally we have:
> 
> `XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/usr/share:/run/host/share:/var/lib/flatpak/exports/share:~/.local/share/flatpak/exports/share:/var/lib/snapd/desktop`
> 
> When I replaced the `~` with the absolute path to my home directory I got all icons to show up, like so:
> 
> `XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/usr/share:/run/host/share:/var/lib/flatpak/exports/share:/var/home/pesader/.local/share/flatpak/exports/share:/var/lib/snapd/desktop`
> Before 	After
> ![image](https://private-user-images.githubusercontent.com/65264536/324134477-08fb90ea-6da1-443d-b6d3-76e286e3447d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDQ3NjIsIm5iZiI6MTcxMzYwNDQ2MiwicGF0aCI6Ii82NTI2NDUzNi8zMjQxMzQ0NzctMDhmYjkwZWEtNmRhMS00NDNkLWI2ZDMtNzZlMjg2ZTM0NDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA5MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTE1OGZmNmMyY2QzZDk5MWI5ODlhYjA4MWFhZWI3ZmI1OWM1MWVmMGUzNzc5MDdlMGZkOTJhZDIwOTY2NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tIUH977zzF-dEtOJtd6zJozDKlph4RTsSYm4ZaYoe74) 	![image](https://private-user-images.githubusercontent.com/65264536/324134496-d9c4e752-8f7c-4a59-ac95-a2d2166e8d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDQ3NjIsIm5iZiI6MTcxMzYwNDQ2MiwicGF0aCI6Ii82NTI2NDUzNi8zMjQxMzQ0OTYtZDljNGU3NTItOGY3Yy00YTU5LWFjOTUtYTJkMjE2NmU4ZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA5MTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YzM1NGI4ZGNmNjEzNmYxODhiNzU2N2E5Y2Q4ZWIwODU0NTYxZmM0YjkzMzY2NjIwZDJhZGIxYWFhNmVjYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CoJ1Umap234KeO5FjaveNxQcSpBApFampddozOV1R5k)
> 
> I suppose that's because `~` is a shell expansion, which won't be interpreted correctly by flatpak. I tried replacing it with `$HOME` but it didn't work. I also checked the manifest of [Mission Center](https://flathub.org/apps/io.missioncenter.MissionCenter), but they use the same `~` in their definition of the `XDG_DATA_DIRS` variable and have the same problem of some icons not showing up.
> 
> Anyway, at least for the time being, this is the workaround.

Thank you so much! I've had this issue of ~ not being resolved before, there's fortunately a Rust crate that will do just that for you. I'll implement that and I think there's gonna be a 1.4.1 release soonish fixing a few bugs including this one. :)
Thanks again for finding it out. :)

**Comment by nokyan** [comment]
I have fixed the bug in the `fix-icons-user-flatpaks` branch, could some of you test it? :)

**Comment by nokyan** [comment]
Perfect, I'm gonna merge it then. :)
