### ISSUE TITLE
Make app title translatable

### ISSUE THREAD

**Issue by lorduskordus** [nokyan/resources#327]
There is a translatable string for the app's name - 'Resources', but the app title in the upper left corner is not affected by it.

![app_title_not_translated](https://github.com/user-attachments/assets/14779364-0cec-4a1d-9c55-2dbeda21eb54)

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I'll fix this after releasing 1.6, I pledged not to make any translation changes until then. :)
