### ISSUE TITLE
Feature Request: support for Intel Arc GPUs

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [nokyan/resources#33]
It would be great if Resources supports Intel Arc GPUs.

My research showed that the gpu utilization seems not to get exposed in the Linux /sys/.../gpu1 structure. 
One might have a look how intel_gpu_top works and gets the gpu load and rebuild something similar in Rust or use this as a ffi lib?
https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/master/tools/intel_gpu_top.c?ref_type=heads

Thanks for your great work!

Edit:
Resources that might help:
https://github.com/Syllo/nvtop/tree/master#intel

**Comment by nokyan** [comment]
Hi, thank you. :)
Intel unfortunately doesn't use GPU stats the same way AMD does using hwmon, [they've reportedly started working on this](https://www.phoronix.com/news/Linux-6.2-HuC-HWMON), but so far it doesn't seem to be there and intel_gpu_top unfortunately requires root access, but I'll see what I can do.

**Comment by LinuxSBC** [comment]
A similar system monitor, Mission Center, added support for Intel GPUs in [this commit](https://gitlab.com/mission-center-devs/mission-center/-/merge_requests/74/diffs?commit_id=bd1311c1a8b4947900613840f2995df8ffc52cfb). Does that help, or are the two projects too different?

**Comment by nokyan** [comment]
Resources should be able to get more stats from Intel GPUs with version 1.3. I'm not sure when it will be released — I'd love to get memory usage under control before — but you can try it out right now if you want to build Resources yourself.

**Comment by houssemko** [comment]
I think mission center uses nvtop as a backend to check intel gpu usage , decode and encode.
is there a way to implement the same utility in resources ?

**Comment by nokyan** [comment]
> I think mission center uses nvtop as a backend to check intel gpu usage , decode and encode. is there a way to implement the same utility in resources ?

Resources will be able to get more stats from Intel GPUs with version 1.3. I hope I can release it to Flathub today. Please tell me right away if something is missing when 1.3 lands as I don't have an Intel GPU to test with.

**Comment by houssemko** [comment]
okay i will .

**Comment by houssemko** [comment]
-video memory usage
-power usage
-temperature
-current power cap 
-max power cap 
all those metrics are missing , using an integrated intel gpu 8th gen : broadwell

**Comment by nokyan** [comment]
> -video memory usage -power usage -temperature -current power cap -max power cap all those metrics are missing , using an integrated intel gpu 8th gen : broadwell

Do you mind installing nvtop and send a screenshot of it running?

**Comment by houssemko** [comment]
![image](https://github.com/nokyan/resources/assets/41808005/76bc600f-3060-42ec-9655-dc458f8d6344)

**Comment by nokyan** [comment]
It seems to be a limitation of the Intel driver then, sorry about that. :/

**Comment by houssemko** [comment]
Yeah , fantastic app though . i wish it had a round app icon similar to the icon theme i have
