### ISSUE TITLE
Bottom elements are cut off in bottom sheets for app info 

### ISSUE THREAD

**Issue by LinuxSBC** [nokyan/resources#333]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When opening the "App Information" bottom sheet (the same applies to "Process Information"), if the window is too short, the bottom elements will be cut off and cannot be scrolled to.
[Screencast from 2024-08-23 23-02-10.webm](https://github.com/user-attachments/assets/16756afb-b801-4395-82bd-470ea2ba6e6b)

### Expected Behavior

When resizing the window, all elements would remain accessible. They might be hidden, but scrolling would reveal them.

### Steps To Reproduce

1. Right click on an app to open "App Information."
2. Scroll to the bottom.
3. Shrink the window until the bottom is cut off.

### Environment

```markdown
Program Version 1.6.0
Package type: Flatpak
System: Fedora Silverblue 40
```

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I can reproduce it, this has been introduced by the change to the new AdwDialog I believe. Maybe I'm not using it correctly, I'll investigate it. :)
