### ISSUE TITLE
NVIDIA GPUs cannot shown after upgarding nvidia drivers on flatpak

### ISSUE THREAD

**Issue by rashadgasimli** [nokyan/resources#334]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

NVIDIA GPUs details cannot shown in GPU 1 (dGPU) section

### Expected Behavior

Most of details is shown in this section

### Steps To Reproduce

1. Open "Resources" app
2. Go to "GPU 1" section
3.  There is no details about NVIDIA GPUs

### Environment

```markdown
Program version: 1.6.0
Package type: Flatpak
System: Arch Linux x86_64
Hardware info: 11th Gen Intel(R) Core(TM) i5-11400H (12) @ 4.50 GHz, NVIDIA GeForce RTX 3050 Mobile [Discrete], Intel UHD Graphics @ 1.45 GHz [Integrated], 32 GB RAM, 512 GB SSD
```

### Anything else?

![Screenshot from 2024-08-24 10-16-35](https://github.com/user-attachments/assets/9e8e40a2-72f1-46fe-9874-1d346ade3dd5)

```
flatpak list | grep nvidia
nvidia-555-58-02	org.freedesktop.Platform.GL.nvidia-555-58-02		1.4	user
nvidia-555-58-02	org.freedesktop.Platform.GL32.nvidia-555-58-02		1.4	user
```

```
nvidia-smi                
Sat Aug 24 10:56:57 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   55C    P0             14W /   75W |       8MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1386      G   /usr/bin/gnome-shell                            1MiB |
+-----------------------------------------------------------------------------------------+

```

**Comment by nokyan** [comment]
Hi, thanks for the issue.
I believe this is usually caused by a mismatch of the versions of the NVIDIA Flatpak platform and the native NVIDIA driver, though they seem to match in your case. I also believe though that this is not a Resources-specific issue. I can reproduce the bug in Resources right now but other Flatpak apps like Prism Launcher for Minecraft also have problems for me (again). In my experience, it tends to go away again once an update for either the Flatplak platform or the native driver is installed.

**Comment by nokyan** [comment]
There's been an issue with the current Flatpak NVIDIA Platforms, it's been addressed and a fix should be up soon: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/288 :)

**Comment by rashadgasimli** [comment]
> There's been an issue with the current Flatpak NVIDIA Platforms, it's been addressed and a fix should be up soon: [flathub/org.freedesktop.Platform.GL.nvidia#288](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/288) :)

Yeah I saw that, it worked after upgrading nvidia drivers. Thanks.
