### ISSUE TITLE
Search options *Feature Request*

### ISSUE THREAD

**Issue by nPHYN1T3** [nokyan/resources#34]
When I fire up a sysmon type tool it's normally because something isn't playing nice. Being able to open it and have search already be visible and the active element is a real time saver. i.e. open and immediately type to filter the offending process so I can get down to MUR-DIDDLY-URDER!

So having options for "Always Show Search" along with "Always Focus Search (on launch)" and a "Show/Focus Search" key combo/short cut would all be fantabulous!

**Comment by nokyan** [comment]
Hi, thank you for the feature request!
A shortcut for opening the search would definitely be a good idea, I think the option will be easy to implement too, it's on my list! :)

**Comment by nokyan** [comment]
Closing this as it's implemented in Resources 1.2. :)
