### ISSUE TITLE
Duplicate info in Processes tab

### ISSUE THREAD

**Issue by lorduskordus** [nokyan/resources#340]
Having both of these settings in Settings --> General enabled:

![Snímek obrazovky 2024-08-25 134307](https://github.com/user-attachments/assets/77624c3e-7c14-432a-86bd-57fad1a40016)

Results in duplicated information for the Processes tab in the sidebar:

![Snímek obrazovky 2024-08-25 135248](https://github.com/user-attachments/assets/d0f54a84-17ce-4b31-8eb5-d3c7f1d47d2e)

**Comment by nokyan** [comment]
Hi, thanks for the issue, fix will be merged shortly. :)
