### ISSUE TITLE
No processes

### ISSUE THREAD

**Issue by schuelermine** [nokyan/resources#357]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

![image](https://github.com/user-attachments/assets/18d55eba-ab82-49e2-9b47-cda3690e7fce)

### Expected Behavior

Not that

### Steps To Reproduce

1. Open the app

### Environment

```markdown
Program Version 1.6.0
Package type: Flatpak
System: NixOS 24.11.20240906.574d1ea (Vicuna)
Hardware info(if applicable): Lenovo Legion Y530-15ICH, CPU: Intel(R) Core(TM) i5-8300H (8) @ 4.00 GHz, Memory: 23.35 GiB
```

**Comment by Henry-Hiles** [comment]
Can reproduce.

**Comment by nokyan** [comment]
Hi, thanks for the issue.
This is a problem with how NixOS works. Resources spawns a process outside the flatpak sandbox and since NixOS (as far as I know) can't run normal binaries, that secondary process will not work. There is a [Nix package](https://search.nixos.org/packages?channel=unstable&show=resources&from=0&size=50&sort=relevance&type=packages&query=resources) though.

**Comment by schuelermine** [comment]
Thanks.

To clarify: NixOS can only run
- binaries built for NixOS with Nix
- fully statically linked libraries (no dynamic loader or libc)
- other binaries if specially configured for them

**Comment by Henry-Hiles** [comment]
Also, why does resources have to spawn a precompiled binary outside of the sandbox?

**Comment by nokyan** [comment]
> Hey! I had the same issue, and I'm on postmarketOS! Other apps like mission control work fine.

I unfortunately don't know anything about postmarketOS, do you mind sending logs with the environment variable `RUST_LOG=resources=debug` set?

> Also, why does resources have to spawn a precompiled binary outside of the sandbox?

Flatpak doesn't allow apps to see other processes at all (i. e. access /proc)

**Comment by Henry-Hiles** [comment]
> > Hey! I had the same issue, and I'm on postmarketOS! Other apps like mission control work fine.
> 
> I unfortunately don't know anything about postmarketOS, do you mind sending logs with the environment variable `RUST_LOG=resources=debug` set?
> 
> > Also, why does resources have to spawn a precompiled binary outside of the sandbox?
> 
> Flatpak doesn't allow apps to see other processes at all (i. e. access /proc)

Sure I'll do the first thing later, and I grasped the second, but you could just spawn a plain shell script or command, no?

**Comment by nokyan** [comment]
> but you could just spawn a plain shell script or command, no?

The secondary process is rather complex (see [lib/process_data/src/lib.rs](https://github.com/nokyan/resources/blob/main/lib/process_data/src/lib.rs) and [src/bin/resources-processes.rs](https://github.com/nokyan/resources/blob/main/src/bin/resources-processes.rs)) and having it also written in Rust allows for more code reusal. I also hate bash's syntax with a burning passion, so writing it in bash was out of the question right from the start. 😅
Python might be an option but then there's still the code reusal problem + additional complexity introduced by needing to call a Python interpreter somewhere + resources-processes needs to be performant, and Python isn't exactly known for performance. :)

**Comment by schuelermine** [comment]
> […] but you could just spawn a plain shell script or command, no?

A shell script is just as non-portable as a dynamic binary.

**Comment by Henry-Hiles** [comment]
oh wait, it probably doesnt work on pmos due to no systemd

**Comment by Henry-Hiles** [comment]
> > but you could just spawn a plain shell script or command, no?
> 
> The secondary process is rather complex (see [lib/process_data/src/lib.rs](https://github.com/nokyan/resources/blob/main/lib/process_data/src/lib.rs) and [src/bin/resources-processes.rs](https://github.com/nokyan/resources/blob/main/src/bin/resources-processes.rs)) and having it also written in Rust allows for more code reusal. I also hate bash's syntax with a burning passion, so writing it in bash was out of the question right from the start. 😅 Python might be an option but then there's still the code reusal problem + additional complexity introduced by needing to call a Python interpreter somewhere + resources-processes needs to be performant, and Python isn't exactly known for performance, same as Bash. :)

hmm, at least to me, it makes sense to have the more complex code within the sandbox, just spawning something to grt data. also, is it not possible to get this data using some permission rather than spawning an external process?

**Comment by Henry-Hiles** [comment]
> > […] but you could just spawn a plain shell script or command, no?
> 
> A shell script is just as non-portable as a dynamic binary.

im not quite sure if thats true, you wouldnt have any trouble running a shell script on nix

**Comment by nokyan** [comment]
> oh wait, it probably doesnt work on pmos due to no systemd

That's not unlikely, at least application detection for sure won't work without systemd.

> hmm, at least to me, it makes sense to have the more complex code within the sandbox, just spawning something to grt data. also, is it not possible to get this data using some permission rather than spawning an external process?

resources-processes already does almost only data obtaining, please see [lib/process_data/src/lib.rs](https://github.com/nokyan/resources/blob/main/lib/process_data/src/lib.rs) and [src/bin/resources-processes.rs](https://github.com/nokyan/resources/blob/main/src/bin/resources-processes.rs). Again, there'd still be the issue of code duplication, added complexity and performance degradation. And no, as I said, Flatpak does not offer any way for an app to see other processes.
