### ISSUE TITLE
Make Y Axis Static for all Graphs

### ISSUE THREAD

**Issue by laktak** [nokyan/resources#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It's not possible to 'glance' at the disk io or network bandwidth because the y axis keeps changing.

### Describe the solution you'd like

Just like that CPU/Memory graphs that have a fixed range, the other graphs should keep the max y range and not jump to the largest value currently displayed.

### Additional context

I'd actually consider this a bug but maybe make this an option, not sure if everyone would agree.

**Comment by nokyan** [comment]
Hi,
the other graphs have a fixed Y range because they're percentages. While you could consider current network speeds as percentages of their max speed (e. g. 1 Gb/s for standard gigabit ethernet) as well, I don't think this makes sense here as most people probably don't come even near their max speed most of the time. Same for drive speeds.

**Comment by laktak** [comment]
I think I did not explain it very well

Currently if you have a graph like this:

    | x       |
    | x   x   |
    | xx  x   |
    |xxxx xxxx|
    -----------

After it moves two cols. to the right it would currently rescale and look like:

    |   x     |
    |x  x   x |
    |x  x   x |
    |xx xxxxxx|
    -----------

I propose that you keep the max value that was shown and the graph continues on like this:

    |         |
    |   x     |
    |x  x   x |
    |xx xxxxxx|
    -----------

This better represents the actual information IMO.

**Comment by nokyan** [comment]
Ah, I understand now.
Still, I'm not quite fond of the idea, one outlier (e. g. in the network graphs one very fast transmission over the local network compared to relatively slow internet speeds) might make the graph pretty much useless. Making this togglable would clutter up the settings window even more in my opinion.

**Comment by laktak** [comment]
As an alternative example, `btop` allows you to set the graph for upload/download by value:

```
╭─┐tab→┌─────────────────────────────────────────────────────────────────────╮
│   1general        2cpu        3gpu        4mem        [net]       6proc    │
├─────────────────────────────┬──────────────────────────────────────────────┤
│       Graph symbol net      │ Fixed network graph download value.          │
│           default           │                                              │
│         Net download        │ Value in Mebibits, default "100".            │
│ ←           100         ↵ → │                                              │
│          Net upload         │ Can be toggled with auto button.             │
│             100             │                                              │
│           Net auto          │                                              │
│             True            │                                              │
│           Net sync          │                                              │
│             True            │                                              │
│          Net iface          │                                              │
│                             │                                              │
│                             │                                              │
│                             │                                              │
```

Would this be more in line with this project?

**Comment by nokyan** [comment]
> As an alternative example, `btop` allows you to set the graph for upload/download by value:
> 
> ```
> ╭─┐tab→┌─────────────────────────────────────────────────────────────────────╮
> │   1general        2cpu        3gpu        4mem        [net]       6proc    │
> ├─────────────────────────────┬──────────────────────────────────────────────┤
> │       Graph symbol net      │ Fixed network graph download value.          │
> │           default           │                                              │
> │         Net download        │ Value in Mebibits, default "100".            │
> │ ←           100         ↵ → │                                              │
> │          Net upload         │ Can be toggled with auto button.             │
> │             100             │                                              │
> │           Net auto          │                                              │
> │             True            │                                              │
> │           Net sync          │                                              │
> │             True            │                                              │
> │          Net iface          │                                              │
> │                             │                                              │
> │                             │                                              │
> │                             │                                              │
> ```
> 
> Would this be more in line with this project?

That would clutter up the settings even more, I'm afraid.

**Comment by laktak** [comment]
I am not sure I understand what you mean with "clutter".

The more powerful a tool gets, the more options it should have. Everybody will want to use the tool differently but by looking for a common denominator you turn it into something less than it could be.

**Comment by nokyan** [comment]
> I am not sure I understand what you mean with "clutter".
> 
> The more powerful a tool gets, the more options it should have. Everybody will want to use the tool differently but by looking for a common denominator you turn it into something less than it could be.

I want to keep a balance between offering options that a lot of people may find useful and have a big impact on how the app is used, and not blowing up the preferences window with endless pages of options a rather small subset of users might theoretically use. Latter is not good application design in my opinion. [This](https://ometer.com/preferences.html) is a quite good read on that.

**Comment by laktak** [comment]
Well I strongly disagree but it's your project. Thanks for your time.
