### ISSUE TITLE
Wrong `Processes`  description with `show device descriptions` option

### ISSUE THREAD

**Issue by d-enk** [nokyan/resources#393]
### Current Behavior

![image](https://github.com/user-attachments/assets/d4e3ed8b-9cf4-4b9d-988b-33df7e97c188)

### Steps To Reproduce

set Show Device Descriptions in Sidebar: true

### Environment

```markdown
Program Version 1.6.0
Package type: Flatpak
System: Ubuntu 24.04
```

**Comment by nokyan** [comment]
Hi,
thanks for the issue. This problem is known and fixed in the main branch. The fix will be released with Resources 1.7, which will likely release on 29 November. :)
