### ISSUE TITLE
Build fails on Manjaro

### ISSUE THREAD

**Issue by seniordevel** [nokyan/resources#398]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Tried to install 1.6.0.r52.g46a50ba-1 with pamac from AUR.
Build is aborted.

Following the last lines of build log:

`The following warnings were emitted during compilation:

warning: libadwaita-sys@0.7.1: 

error: failed to run custom build command for `libadwaita-sys v0.7.1`

Caused by:
  process didn't exit successfully: `/var/tmp/pamac-build-ik/resources-git/src/build/src/debug/build/libadwaita-sys-ba370bcbe53b351d/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=/var/tmp/pamac-build-ik/resources-git/src/build/cargo/registry/src/index.crates.io-6f17d22bba15001f/libadwaita-sys-0.7.1/Cargo.toml
  cargo:rerun-if-env-changed=LIBADWAITA_1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libadwaita-1 libadwaita-1 >= 1.6

  The system library `libadwaita-1` required by crate `libadwaita-sys` was not found.
  The file `libadwaita-1.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `libadwaita-1.pc`.

warning: build failed, waiting for other jobs to finish...
FAILED: src/debug 
/usr/bin/env CARGO_HOME=/var/tmp/pamac-build-ik/resources-git/src/build/cargo /usr/bin/cargo build --manifest-path /var/tmp/pamac-build-ik/resources-git/src/resources/Cargo.toml --target-dir /var/tmp/pamac-build-ik/resources-git/src/build/src
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /var/tmp/pamac-build-ik/resources-git/src/build
==> ERROR: A failure occurred in build().
    Aborting...

`

### Expected Behavior

---

### Steps To Reproduce

Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.8.0
Qt Version: 6.7.2
Kernel Version: 6.10.13-3-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G
Memory: 14,6 GiB of RAM
Graphics Processor: KAVERI

### Environment

```markdown
---
```

**Comment by nokyan** [comment]
Hi,
I don't maintain the AUR package and thus can't really offer support for it. I'd recommend you to try the Flatpak release on Flathub.
Looking through the logs, libadwaita apparently wasn't found. Can you confirm whether it is installed?

**Comment by seniordevel** [comment]
![Screenshot_20241114_195537](https://github.com/user-attachments/assets/7da89fb1-1835-4dbe-96a8-58fc27885685)

libadwaita seems to bee installed.

> I'd recommend you to try the Flatpak release on Flathub.
I looked for it, but pamac failed to find this Flathub package. Usually it always finds a Flathub package, but now it fails.
Maybe I used the wrong keyword (?), I just used 'resources' for the search.

**Comment by nokyan** [comment]
I see that your installed libadwaita version is 1.5.4, Resources requires 1.6 though. You could update your system and try again. If it's still at 1.5.4, I guess Manjaro holds it back for supposed stability.
You could also try pulling the repo from GitHub and building it yourself.
Or, again, if you just want to use Resources, I recommend using the Flathub release. Alternatively, Resources (the release version) is also in Arch's extra repository, I wouldn't recommend the -git version from the AUR for daily usage in general.

**Comment by seniordevel** [comment]
> Or, again, if you just want to use Resources, I recommend using the Flathub release
Thank you, this worked for me now (using discover app manager)
