### ISSUE TITLE
Wrong Video memory usage

### ISSUE THREAD

**Issue by Glucy-2** [nokyan/resources#409]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

![image](https://github.com/user-attachments/assets/578982f2-c2b2-4cc6-a23e-4e82c5512819)
![image](https://github.com/user-attachments/assets/0c454403-6d65-4d05-875c-e2c3e1bd652a)
The Video memory displayed in the program is wrong

### Environment

```markdown
Program Version 1.7.0
Package type: Flatpak
System: ArchLinux
Hardware info: AMD 7840HS with Radeon 780M Graphics
```

**Comment by awumii** [comment]
Try changing data unit prefix to binary (in the preferences menu)
![obraz](https://github.com/user-attachments/assets/4fd82c1c-1b81-4549-8f3b-794d90fab953)
![obraz](https://github.com/user-attachments/assets/01dd6622-2b76-43d2-aae6-9925d9ab168f)

**Comment by Glucy-2** [comment]
OK
