### ISSUE TITLE
Track total IO use (disk data written)

### ISSUE THREAD

**Issue by sh7dm** [nokyan/resources#48]
Done by gnome-system-monitor (see disk write/read total):
![image](https://github.com/nokyan/resources/assets/19504461/5c309f95-1c1b-4e98-ae79-5f5fd5f7282c)

**Comment by nokyan** [comment]
Hi!
Resources currently doesn't track that for processes, I'll put it on my list. :)

**Comment by sh7dm** [comment]
Researched this a bit: this's handled by [read_bytes and write_bytes](https://github.com/torvalds/linux/blob/05d3ef8bba77c1b5f98d941d8b2d4aeab8118ef1/Documentation/filesystems/proc.rst#write_bytes) in `/proc/PID/io` file. `rchar` and `wchar` are _not_ relevant to measuring disk usage as they count device I/O usage as well.
