### ISSUE TITLE
Non-existent disk partitions are shown

### ISSUE THREAD

**Issue by Nindaleth** [nokyan/resources#51]
My single-partition SSD is shown as the one valid /dev/sda partition and then several empty partitions (/dev/sdb, /dev/sdc...). I'm running Flatpak on Fedora 38:

![partitions](https://github.com/nokyan/resources/assets/6383928/8d5e2746-8594-4373-84f5-cf800547644b)

The actual disk layout:

![sda](https://github.com/nokyan/resources/assets/6383928/b361b459-3479-47dc-a156-80d46b403efd)

**Comment by nokyan** [comment]
Hi, thanks for reporting the issue.
I didn't know about this btrfs feature, since I'm currently implementing a switch for showing virtual drives anyways, I'll also include those 0 B "drives" so you can toggle their visibility.

**Comment by Nindaleth** [comment]
I've logged the same issue for Mission Center and its dev suggested something that turned out to be the root cause - these empty drives are actually provided by an SD card reader (that has no cards in it).

**Comment by nokyan** [comment]
Forgot to close this one as it should be fixed with 1.2.1 :)

**Comment by Nindaleth** [comment]
Looking good now, thanks for the fix!
