### ISSUE TITLE
Optimization: remember the "Show usages of Logical CPUs" option.

### ISSUE THREAD

**Issue by WhoChangedMyCode** [nokyan/resources#67]
When you reopen the app, you can remember the "Show usages of Logical CPUs" option in the "Processor" that you have set before. For me, I like to turn on this option, but every time I reopen the app, I have to open it again manually.

Addendum: I'm using ArchLinux and installed the app via AUR, I don't know if this happens with Flatpak or not!

**Comment by nokyan** [comment]
Hi, thanks for the suggestion.
That's a good idea, I'll include that. :)
