### ISSUE TITLE
Display nothing in Applications and Processes sections on NixOS

### ISSUE THREAD

**Issue by RAVENz46** [nokyan/resources#76]
On applications section, there is a only "System Processes 0B 0%" and on processes section, literary nothing.
Should I give this app to any additional permission by flatseal or something? Or this is because NixOS?
Thank you.

OS: NixOS 23.11.20231016.ca012a0 (Tapir) x86_64
resources: installed from flatpak ver. 1.1.0 stable

**Comment by nokyan** [comment]
Hi,
Resources comes with all the permission it needs, though I frankly don't know anything about NixOS. Do you use systemd? I know from testing in Alpine Linux that Resources doesn't work too well without systemd.

**Comment by RAVENz46** [comment]
@nokyan Yes, use systemd.

**Comment by eitch** [comment]
I have the same issue. Newly installed Ubuntu 23.10 with latest flatpak and your app. It doesn't even show the size of my disks, just lists them all:

![image](https://github.com/nokyan/resources/assets/245382/faf1c0e1-3407-46f2-8c18-5b422263591c)

**Comment by eitch** [comment]
I do see the following error in the log:

```
 INFO  resources::application > Resources (net.nokyan.Resources)
 INFO  resources::application > Version: 1.1.0 ()
 INFO  resources::application > Datadir: /app/share/resources
 DEBUG resources::application::imp > GtkApplication<Application>::startup
 DEBUG resources::application::imp > GtkApplication<Application>::activate
thread 'main' panicked at src/ui/pages/cpu.rs:275:18:
already borrowed: BorrowMutError
stack backtrace:
   0:     0x55e75d7b9d2c - <unknown>
   1:     0x55e75d7e805c - <unknown>
   2:     0x55e75d7b5efe - <unknown>
   3:     0x55e75d7b9b14 - <unknown>
   4:     0x55e75d7bb5a3 - <unknown>
```

**Comment by nokyan** [comment]
> I do see the following error in the log:
> 
> ```
>  INFO  resources::application > Resources (net.nokyan.Resources)
>  INFO  resources::application > Version: 1.1.0 ()
>  INFO  resources::application > Datadir: /app/share/resources
>  DEBUG resources::application::imp > GtkApplication<Application>::startup
>  DEBUG resources::application::imp > GtkApplication<Application>::activate
> thread 'main' panicked at src/ui/pages/cpu.rs:275:18:
> already borrowed: BorrowMutError
> stack backtrace:
>    0:     0x55e75d7b9d2c - <unknown>
>    1:     0x55e75d7e805c - <unknown>
>    2:     0x55e75d7b5efe - <unknown>
>    3:     0x55e75d7b9b14 - <unknown>
>    4:     0x55e75d7bb5a3 - <unknown>
> ``` 

Could you tell me what CPU you're using?

**Comment by eitch** [comment]
Sure: AMD Ryzen 9 7950X3D 16-Core Processor

**Comment by nokyan** [comment]
> Sure: AMD Ryzen 9 7950X3D 16-Core Processor

I'm pretty sure your issue is related to #43 then, it's probably got something to do with your CPU having quite a lot of threads. I have released Resources 1.2.0 today, could you upgrade and test whether the crash still occurs?

**Comment by eitch** [comment]
You are right. Thanks the update works! Is it possible to hide loop devices? Those show up now.

Could you perhaps display up to 8 Threads in a row?

**Comment by nokyan** [comment]
> You are right. Thanks the update works! Is it possible to hide loop devices? Those show up now.
> 
> Could you perhaps display up to 8 Threads in a row?

They should be hidden by default, there is a setting for that in the Settings (accessible via the hamburger menu in the sidebar)

**Comment by eitch** [comment]
> > You are right. Thanks the update works! Is it possible to hide loop devices? Those show up now.
> 
> They should be hidden by default, there is a setting for that in the Settings (accessible via the hamburger menu in the sidebar)
Doesn't seem to change anything:
![image](https://github.com/nokyan/resources/assets/245382/381c8b7f-ad7d-4851-bfea-ff25a0748b06)

> 
> > Could you perhaps display up to 8 Threads in a row?
> 
> I'll see if I can make it reasonably fit. :)
Awesome! I am already loving this app!

![image](https://github.com/nokyan/resources/assets/245382/df37443f-e101-4478-b6df-d02186d0b2b5)

**Comment by nokyan** [comment]
> Doesn't seem to change anything:

I think I found the issue, an oversight of mine in the drive type detection, whoops. 😅
I'll see if I can collect and fix some more smaller bugs and look into the original NixOS issue and release 1.2.1 in a few days or so.

> Awesome! I am already loving this app!

Thank you! :)

**Comment by RAVENz46** [comment]
Sadly, I updated to 1.2.0 and still have issue.
Tried launch from command but it show only these.
BTW, I use Intel 8700.
`$ flatpak run net.nokyan.Resources
 INFO  resources::application > Resources (net.nokyan.Resources)
 INFO  resources::application > Version: 1.2.0 ()
 INFO  resources::application > Datadir: /app/share/resources
 DEBUG resources::application::imp > GtkApplication<Application>::startup
 DEBUG resources::application::imp > GtkApplication<Application>::activate`

**Comment by nokyan** [comment]
> Sadly, I updated to 1.2.0 and still have issue. Tried launch from command but it show only these. BTW, I use Intel 8700.
> 
> ```
> $ flatpak run net.nokyan.Resources
>  INFO  resources::application > Resources (net.nokyan.Resources)
>  INFO  resources::application > Version: 1.2.0 ()
>  INFO  resources::application > Datadir: /app/share/resources
>  DEBUG resources::application::imp > GtkApplication<Application>::startup
>  DEBUG resources::application::imp > GtkApplication<Application>::activate
> ```

So I've installed NixOS in a VM and I was able to reproduce your issue.
Resources needs to launch a seperate executable outside the flatpak sandbox in order to get information about running processes. Apparently NixOS does not support running ordinary executables. I'm gonna do some further research to find out how NixOS works and if Resources' approach to gathering process info is even possible on NixOS.

**Comment by RAVENz46** [comment]
Wow, thank you.
To tell you the truth, I have not been using NixOS for long, so I am limited in what I can do, but I will tell you that [nix-init](https://github.com/nix-community/nix-init) makes the build itself easy.
Unfortunately, when I tried it myself, the build failed because the version of libadwaita on the nixpkgs side was bit old.

**Comment by Lukas-Heiligenbrunner** [comment]
I've created my own derivation for nixos: 

```
# resources.nix
{ lib
, stdenv
, fetchFromGitHub
, appstream-glib
, cargo
, git
, desktop-file-utils
, meson
, ninja
, pkg-config
, rustPlatform
, rustc
, wrapGAppsHook4
, glib
, gtk4
, libadwaita
}:

stdenv.mkDerivation rec {
  pname = "resources";
  version = "1.2.1";

  src = fetchFromGitHub {
    owner = "nokyan";
    repo = pname;
    rev = "refs/tags/v${version}";
    hash = "sha256-OB8ccuynnmv+59M988a4rS2xkcpYQhyYOJzDnK0fA2Y=";
  };


  postPatch = ''
    patchShebangs build-aux
  '';

  cargoDeps = rustPlatform.fetchCargoTarball {
    inherit src;
    name = "${pname}-${version}";
    hash = "sha256-uH/E0poWcm1Aj1aS9ZAe42feg4HoID3x/iYeAH6BbAI=";
  };

  nativeBuildInputs = [
    appstream-glib
    desktop-file-utils
    meson
    ninja
    pkg-config
    wrapGAppsHook4
    rustPlatform.cargoSetupHook
    cargo
    git
    rustc
  ];

  buildInputs = [
    glib
    gtk4
    libadwaita
  ];

  meta = {
    description = "Resources";
    homepage = "https://github.com/nokyan/resources";
    license = lib.licenses.gpl3Only;
    maintainers = with lib.maintainers; [ dotlambda foo-dogsquared ];
    platforms = lib.platforms.all;
  };
}
```

You can add this to your configuration.nix in the systemppkgs section by calling it with 
`(pkgs.callPackage ./resources.nix { })`

I'm still a nixos beginner so it might be not the best/most elegant way. 
However, resources thinks itself its a devel version, so I think I'd still need to set some config variables. 
But the rest seems to work fine for me. :)

**Comment by Lukas-Heiligenbrunner** [comment]
My PR for nixpkgs was just merged and should land on unstable soon :)
https://github.com/NixOS/nixpkgs/pull/270250
