### ISSUE TITLE
Resources now shows around 20 loop devices.

### ISSUE THREAD

**Issue by diegorodriguezv** [nokyan/resources#84]
Resources 1.1 used to show only my physical drives. 
After 1.2 it now shows around 20 loop devices, probably used for snaps in ubuntu.
These loop devices are not physical drives and make finding real drives difficult.
Could you filter them? 
They are located at `/dev/loopX` where X is a number.
This is probably related to issue #21.
Reference [link](https://askubuntu.com/questions/906581/what-is-dev-loopx)
Thanks.

**Comment by nokyan** [comment]
Sorry for the inconvenience, I've already located the issue and this should be fixed with Resources 1.2.1 which I plan to release in a few days. :)
