### ISSUE TITLE
Feature request: manual dark mode override

### ISSUE THREAD

**Issue by liu2g** [nokyan/resources#89]
Hello, thanks for making the amazing software! I would like to ask if it is possible to have a manual override to dark/light mode? I assume such info is probably queried from DE but in a bare WM environment (I am using i3-wm), having a programs just to put a global dark mode flag into the X session can be a hassle. It would be great if such option is available in the Preferences menu. 

Edit: I am using version 1.2.1 and there is no such option as of now

![image](https://github.com/nokyan/resources/assets/55007630/66ec3c1c-e2fe-4c9f-b04d-cba0a80dc7d9)

**Comment by Belarrius1** [comment]
I want this feature too :)

**Comment by nokyan** [comment]
Doesn't `gsettings set org.gnome.desktop.interface color-scheme prefer-dark` work?

**Comment by liu2g** [comment]
Unfortunately, my system setup does not use any GTK settings, dconf, etc. other than [lxappearance](https://github.com/lxde/lxappearance) in terms of themes. However, I do found out a workaround by setting `GTK_THEME=Adwaita-dark` to my `.profile`, which is an acceptable solution. I am closing this issue and if anyone else has better solution feel free to comment below
