### ISSUE TITLE
Apply to join GNOME Circle

### ISSUE THREAD

**Issue by julianfairfax** [nokyan/resources#97]
Applying to join [GNOME Circle](https://apps.gnome.org/en-GB/#circle) would give the app greater visibility within the GNOME ecosystem.

**Comment by nokyan** [comment]
Hi,
thanks for the suggestion. There's one or two things (GPU per-process stats support and fixing the memory leak) that I'd like to do before I apply for GNOME Circle or GNOME World. :)

**Comment by nokyan** [comment]
> > There's one or two things (GPU per-process stats support and fixing the memory leak) that I'd like to do before I apply for GNOME Circle or GNOME World. :)
> 
> Once those are done, I'd actually argue you should apply for GNOME Incubation (to be accepted as a core app). This app could easily replace the GNOME System Monitor app, which doesn't have an up-to-date design, and the GNOME Usage app, which doesn't have a lot of features.

That's a good idea as well, I'll consider it once I find the time to improve accessibility and QoL (and hopefully further improve memory usage, it's still bugging me), which will be the main focus points for release 1.4. Right now I'm quite busy with my studies and other stuff, so I unfortunately don't have too much time on my hands for Resources (as evident by the rather few commits the last week or so).

**Comment by nokyan** [comment]
Resources has been [accepted](https://fosstodon.org/@bragefuglseth/113012086701003753) into GNOME circle!
