### ISSUE TITLE
Opera categorized as a system process

### ISSUE THREAD

**Issue by Zoobdude** [nokyan/resources#98]
![image](https://github.com/nokyan/resources/assets/96008479/85b77509-161f-4e27-b0fc-a1928e509918)

![image](https://github.com/nokyan/resources/assets/96008479/f8bac675-8b25-4a86-86f2-6047594272f3)

**Comment by nokyan** [comment]
Hi,
can you please give more information when reporting bugs? Which operating system are you using? Did you install Opera natively?

**Comment by Zoobdude** [comment]
Sorry for being so vague. 

OS: Ubuntu 23.10
Opera installed via Snap

**Comment by nokyan** [comment]
I'll look into it.

**Comment by nokyan** [comment]
So it seems that Resources doesn't recognize apps that were installed using Snap. I'll see if I can make it work, shouldn't be too hard if snap properly exposes application data.

**Comment by nokyan** [comment]
Closing this because it has been resolved with Resources 1.3 (still not on Flathub unfortunately). If there's still an issue related to this, don't hesitate to reopen :)
